import type {EmergencyContactDoc,SavedEmergencyFacilityDoc} from '../types';

type CachePayload={facilities:SavedEmergencyFacilityDoc[];contacts:EmergencyContactDoc[];centralFacilities:SavedEmergencyFacilityDoc[];cachedAt:number};
const DB_NAME='momhaven-emergency';const DB_VERSION=1;const STORE='emergency-data';
const memoryCache=new Map<string,CachePayload>();

function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(new Error('IndexedDB unavailable'));return}const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function merge(payload:CachePayload|null):CachePayload|null{if(!payload)return null;const central=payload.centralFacilities||[];const own=payload.facilities||[];const ids=new Set(own.map(item=>item.id));return {...payload,facilities:[...own,...central.filter(item=>!ids.has(item.id))]}}
export async function readEmergencyCache(userId:string){const memory=merge(memoryCache.get(userId)||null);if(memory)return memory;try{const db=await openDb();const value=await new Promise<CachePayload|null>((resolve,reject)=>{const request=db.transaction(STORE,'readonly').objectStore(STORE).get(userId);request.onsuccess=()=>resolve((request.result as CachePayload|undefined)||null);request.onerror=()=>reject(request.error)});const merged=merge(value);if(merged)memoryCache.set(userId,merged);return merged}catch{return null}}
export async function writeEmergencyCache(userId:string,facilities:SavedEmergencyFacilityDoc[],contacts:EmergencyContactDoc[],centralFacilities:SavedEmergencyFacilityDoc[]=[]){const payload:CachePayload={facilities:facilities.filter(f=>!centralFacilities.some(c=>c.id===f.id)),contacts,centralFacilities,cachedAt:Date.now()};memoryCache.set(userId,payload);try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(payload,userId);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{}}
export async function writeCentralEmergencyFacilities(userId:string,facilities:SavedEmergencyFacilityDoc[]){const existing=await readEmergencyCache(userId);await writeEmergencyCache(userId,existing?.facilities||[],existing?.contacts||[],facilities)}
