import { Router, Request, Response } from 'express';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { adminAuth, adminDb, ApiError, logAudit, serialize } from '../clinicianAccess.js';
import { invalidateSafetyCache } from '../safetyConfig.js';

export const adminRouter=Router();
async function requireAdmin(req:Request){const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))throw new ApiError(401,'Sign-in required.');let token;try{token=await adminAuth.verifyIdToken(h.slice(7));}catch{throw new ApiError(401,'Sign-in required.');}const user=await adminDb.doc(`users/${token.uid}`).get();if(!user.exists||user.data()?.role!=='ADMIN')throw new ApiError(403,'Admin access required.');return token;}
function sendError(res:Response,e:any){res.status(e instanceof ApiError?e.status:500).json({error:e?.message||'Unable to complete request.'});}
const clean=(x:any)=>serialize(x);
const list=async(name:string,limit=1000)=>{const q=await adminDb.collection(name).limit(limit).get();return q.docs.map(d=>({id:d.id,...clean(d.data())}));};

adminRouter.get('/dashboard',async(req,res)=>{try{const token=await requireAdmin(req);const[facilities,clinicians,governance,gates,audits]=await Promise.all([adminDb.collection('facilities').limit(1000).get(),adminDb.collection('clinicians').limit(1000).get(),adminDb.collection('clinicalDecisionRegister').limit(1000).get(),adminDb.collection('releaseGates').limit(100).get(),adminDb.collection('auditEvents').limit(500).get()]);const weekAgo=Date.now()-7*24*60*60*1000;const safetyAlerts=audits.docs.filter(d=>{const x=d.data();const t=x.timestamp instanceof Timestamp?x.timestamp.toDate().getTime():new Date(x.timestamp||0).getTime();return t>=weekAgo&&String(x.action||'').toUpperCase().includes('SAFETY');}).length;const pending=clinicians.docs.filter(d=>d.data()?.verificationStatus==='pending').length;const openGovernance=governance.docs.filter(d=>!['approved','clinically_reviewed','source_verified','closed','verified'].includes(String(d.data()?.status||'').toLowerCase())).length;const gatesOut=gates.docs.map(d=>({id:d.id,...clean(d.data())}));const blockedOrOpen=gatesOut.filter(g=>['blocked','open'].includes(String(g.status||'').toLowerCase())).length;const assessed=gatesOut.filter(g=>g.status&&!['unassessed','pending'].includes(String(g.status).toLowerCase())).length;const activity=audits.docs.map(d=>d.data()).filter(x=>{const t=String(x.objectType||'').toLowerCase();return!['pregnan','child','patient','haven','clinicalrecord','privatenote'].some(v=>t.includes(v));}).sort((a,b)=>{const at=a.timestamp instanceof Timestamp?a.timestamp.toMillis():new Date(a.timestamp||0).getTime();const bt=b.timestamp instanceof Timestamp?b.timestamp.toMillis():new Date(b.timestamp||0).getTime();return bt-at;}).slice(0,20).map(x=>({time:clean(x.timestamp),actorId:String(x.actorId||''),action:String(x.action||''),detail:`${String(x.objectType||'')} · ${String(x.objectId||'')}`}));res.json({stats:{activeFacilities:facilities.size,pendingClinicianVerification:pending,openGovernanceItems:openGovernance,safetyAlertsThisWeek:safetyAlerts},release:{gates:gatesOut,blockedOrOpen,total:gatesOut.length,assessed},activity,scope:'National'});await logAudit(token.uid,'ADMIN','ADMIN_DASHBOARD_VIEWED','adminDashboard',token.uid);}catch(e){sendError(res,e);}});

adminRouter.get('/facilities',async(req,res)=>{try{await requireAdmin(req);res.json({items:await list('facilities')});}catch(e){sendError(res,e);}});
adminRouter.post('/facilities',async(req,res)=>{try{const token=await requireAdmin(req);const b=req.body||{};const required=['name','kmhflCode','county','subcounty','contactPhone'];if(required.some(k=>!String(b[k]||'').trim()))throw new ApiError(400,'Name, KMHFL code, county, subcounty and contact phone are required.');const ref=adminDb.collection('facilities').doc();await ref.set({name:String(b.name).trim(),kmhflCode:String(b.kmhflCode).trim(),county:String(b.county).trim(),subcounty:String(b.subcounty).trim(),contactPhone:String(b.contactPhone).trim(),level:b.level?String(b.level).trim():null,ambulanceAvailable:b.ambulanceAvailable===true,maternityWardAvailable:b.maternityWardAvailable===true,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await logAudit(token.uid,'ADMIN','FACILITY_CREATED','facilities',ref.id);res.status(201).json({id:ref.id});}catch(e){sendError(res,e);}});
adminRouter.patch('/facilities/:id',async(req,res)=>{try{const token=await requireAdmin(req);const ref=adminDb.doc(`facilities/${req.params.id}`);if(!(await ref.get()).exists)throw new ApiError(404,'Facility not found.');const allowed=['name','kmhflCode','county','subcounty','contactPhone','level','ambulanceAvailable','maternityWardAvailable'];const patch:any={};for(const k of allowed)if(req.body?.[k]!==undefined)patch[k]=typeof req.body[k]==='string'?req.body[k].trim():req.body[k];patch.updatedAt=FieldValue.serverTimestamp();await ref.update(patch);await logAudit(token.uid,'ADMIN','FACILITY_UPDATED','facilities',ref.id);res.json({success:true});}catch(e){sendError(res,e);}});

adminRouter.get('/clinicians',async(req,res)=>{try{await requireAdmin(req);const q=await adminDb.collection('clinicians').limit(1000).get();const items=await Promise.all(q.docs.map(async d=>{const c=d.data();const u=await adminDb.doc(`users/${d.id}`).get();return{id:d.id,...clean(c),displayName:u.data()?.displayName||u.data()?.email||d.id,email:u.data()?.email||''};}));res.json({items});}catch(e){sendError(res,e);}});
adminRouter.get('/clinicians/:id',async(req,res)=>{try{await requireAdmin(req);const c=await adminDb.doc(`clinicians/${req.params.id}`).get();if(!c.exists)throw new ApiError(404,'Clinician not found.');const u=await adminDb.doc(`users/${req.params.id}`).get();res.json({clinician:{id:c.id,...clean(c.data()),displayName:u.data()?.displayName||u.data()?.email||c.id,email:u.data()?.email||''}});}catch(e){sendError(res,e);}});
async function clinicianStatus(req:Request,res:Response,status:'approved'|'rejected'|'suspended'){try{const token=await requireAdmin(req);const ref=adminDb.doc(`clinicians/${req.params.clinicianId}`);const snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Clinician not found.');const patch:any={verificationStatus:status,updatedAt:FieldValue.serverTimestamp()};if(status==='rejected')patch.rejectionReason=String(req.body?.reason||'').trim()||'Verification request was not approved.';await ref.update(patch);await logAudit(token.uid,'ADMIN',status==='approved'?'CLINICIAN_APPROVED':status==='rejected'?'CLINICIAN_REJECTED':'CLINICIAN_SUSPENDED','clinicians',ref.id,snap.data()?.facilityId||null);res.json({success:true,verificationStatus:status});}catch(e){sendError(res,e);}}
adminRouter.post('/clinician/:clinicianId/approve',(q,s)=>void clinicianStatus(q,s,'approved'));adminRouter.post('/clinician/:clinicianId/reject',(q,s)=>void clinicianStatus(q,s,'rejected'));adminRouter.post('/clinician/:clinicianId/suspend',(q,s)=>void clinicianStatus(q,s,'suspended'));

adminRouter.get('/governance',async(req,res)=>{try{await requireAdmin(req);res.json({items:await list('clinicalDecisionRegister',500)});}catch(e){sendError(res,e);}});
adminRouter.get('/governance/:id',async(req,res)=>{try{await requireAdmin(req);const s=await adminDb.doc(`clinicalDecisionRegister/${req.params.id}`).get();if(!s.exists)throw new ApiError(404,'Clinical rule not found.');res.json({item:{id:s.id,...clean(s.data())}});}catch(e){sendError(res,e);}});
adminRouter.patch('/governance/:id',async(req,res)=>{try{const token=await requireAdmin(req);const status=String(req.body?.status||'');const allowed=['proposed','open','source_verified','needs_clinical_review','citation_not_verified','clinically_reviewed','approved','implemented','tested','blocked','deferred','retired'];if(!allowed.includes(status))throw new ApiError(400,'Invalid governance status.');const ref=adminDb.doc(`clinicalDecisionRegister/${req.params.id}`);const before=await ref.get();if(!before.exists)throw new ApiError(404,'Clinical rule not found.');const now=new Date().toISOString();const history=Array.isArray(before.data()?.reviewHistory)?before.data()?.reviewHistory:[];history.push({from:before.data()?.status||null,to:status,changedAt:now,changedBy:token.uid});await ref.update({status,reviewHistory:history,updatedAt:FieldValue.serverTimestamp()});await logAudit(token.uid,'ADMIN','CLINICAL_DECISION_STATUS_CHANGED','clinicalDecisionRegister',req.params.id);res.json({success:true,status,reviewHistory:history});}catch(e){sendError(res,e);}});

adminRouter.get('/release',async(req,res)=>{try{await requireAdmin(req);res.json({items:await list('releaseGates',100)});}catch(e){sendError(res,e);}});
adminRouter.get('/release/:id',async(req,res)=>{try{await requireAdmin(req);const s=await adminDb.doc(`releaseGates/${req.params.id}`).get();if(!s.exists)throw new ApiError(404,'Release gate not found.');res.json({item:{id:s.id,...clean(s.data())}});}catch(e){sendError(res,e);}});
adminRouter.patch('/release/:id',async(req,res)=>{try{const token=await requireAdmin(req);const status=String(req.body?.status||'unassessed');if(!['unassessed','open','blocked','approved'].includes(status))throw new ApiError(400,'Invalid release status.');const ref=adminDb.doc(`releaseGates/${req.params.id}`);const before=await ref.get();if(!before.exists)throw new ApiError(404,'Release gate not found.');const evidence=Array.isArray(req.body?.evidence)?req.body.evidence:undefined;const patch:any={status,updatedAt:FieldValue.serverTimestamp()};if(evidence)patch.evidence=evidence;const signOffs=Array.isArray(before.data()?.signOffs)?before.data()?.signOffs:[];if(req.body?.signOff)signOffs.push({adminId:token.uid,at:new Date().toISOString(),note:String(req.body.signOff)});patch.signOffs=signOffs;await ref.update(patch);await logAudit(token.uid,'ADMIN','RELEASE_GATE_UPDATED','releaseGates',ref.id);res.json({success:true});}catch(e){sendError(res,e);}});

adminRouter.get('/safety-patterns',async(req,res)=>{try{await requireAdmin(req);res.json({items:await list('safetyPatterns',500)});}catch(e){sendError(res,e);}});
adminRouter.post('/safety-patterns',async(req,res)=>{try{const token=await requireAdmin(req);const b=req.body||{};if(!['mother','newborn','child','selfharm'].includes(b.category)||!String(b.label||'').trim()||!Array.isArray(b.matchPatterns)||!b.matchPatterns.length)throw new ApiError(400,'Category, label and at least one trigger phrase are required.');const ref=adminDb.collection('safetyPatterns').doc();await ref.set({id:ref.id,category:b.category,label:String(b.label).trim(),icon:String(b.icon||'shield-alert'),matchPatterns:b.matchPatterns.map(String),version:1,enabled:b.enabled!==false,updatedAt:FieldValue.serverTimestamp(),updatedBy:token.uid,versionHistory:[{version:1,at:new Date().toISOString(),by:token.uid,matchPatterns:b.matchPatterns.map(String)}]});invalidateSafetyCache();await logAudit(token.uid,'ADMIN','SAFETY_PATTERN_CREATED','safetyPatterns',ref.id);res.status(201).json({id:ref.id});}catch(e){sendError(res,e);}});
adminRouter.patch('/safety-patterns/:id',async(req,res)=>{try{const token=await requireAdmin(req);const ref=adminDb.doc(`safetyPatterns/${req.params.id}`);const before=await ref.get();if(!before.exists)throw new ApiError(404,'Safety pattern not found.');const b=req.body||{};const current=before.data()||{};const patch:any={updatedAt:FieldValue.serverTimestamp(),updatedBy:token.uid};if(b.label!==undefined)patch.label=String(b.label).trim();if(b.icon!==undefined)patch.icon=String(b.icon);if(b.category!==undefined&&['mother','newborn','child','selfharm'].includes(b.category))patch.category=b.category;if(b.enabled!==undefined)patch.enabled=Boolean(b.enabled);if(Array.isArray(b.matchPatterns)){const version=Number(current.version||0)+1;patch.matchPatterns=b.matchPatterns.map(String);patch.version=version;patch.versionHistory=[...(Array.isArray(current.versionHistory)?current.versionHistory:[]),{version,at:new Date().toISOString(),by:token.uid,matchPatterns:patch.matchPatterns}];}await ref.update(patch);invalidateSafetyCache();await logAudit(token.uid,'ADMIN','SAFETY_PATTERN_UPDATED','safetyPatterns',ref.id);res.json({success:true,version:patch.version||current.version});}catch(e){sendError(res,e);}});

adminRouter.get('/content',async(req,res)=>{try{await requireAdmin(req);res.json({items:await list('educationalContent',500)});}catch(e){sendError(res,e);}});
adminRouter.patch('/content/:id',async(req,res)=>{try{const token=await requireAdmin(req);const status=String(req.body?.status||'draft');if(!['draft','published','archived'].includes(status))throw new ApiError(400,'Invalid content status.');await adminDb.doc(`educationalContent/${req.params.id}`).update({status,updatedAt:FieldValue.serverTimestamp()});await logAudit(token.uid,'ADMIN','EDUCATIONAL_CONTENT_STATUS_CHANGED','educationalContent',req.params.id);res.json({success:true});}catch(e){sendError(res,e);}});
adminRouter.get('/audit',async(req,res)=>{try{await requireAdmin(req);const items=(await list('auditEvents',500)).filter((x:any)=>{const t=String(x.objectType||'').toLowerCase();return!['pregnan','child','patient','haven','clinicalrecord','privatenote'].some(v=>t.includes(v));});res.json({items});}catch(e){sendError(res,e);}});
