import { Router, Request, Response } from 'express';
import { adminAuth, adminDb, ApiError, document, logAudit, requireActiveSession, requireClinician, serialize } from '../clinicianAccess';
import { FieldValue } from 'firebase-admin/firestore';
import { CLINICAL_RECORD_GROUPS, getPatientRecords } from '../services/patientRecordService';

export const clinicianRouter = Router();

async function auth(req: Request) {
  const header = String(req.headers.authorization || '');
  if (!header.startsWith('Bearer ')) throw new ApiError(401, 'Sign-in required.');
  try { return await adminAuth.verifyIdToken(header.slice(7)); } catch { throw new ApiError(401, 'Sign-in required.'); }
}
function sendError(res: Response, e: any) { const status = e instanceof ApiError ? e.status : 500; res.status(status).json({ error: e?.message || 'Unable to complete request.' }); }
async function clinician(req: Request) { const token = await auth(req); await requireClinician(token.uid); return token; }
async function motherName(motherId: string) {
  const p = await adminDb.doc(`motherProfiles/${motherId}`).get();
  if (p.exists && p.data()?.fullName) return String(p.data()!.fullName);
  const u = await adminDb.doc(`users/${motherId}`).get();
  return String(u.data()?.displayName || u.data()?.email || 'Mother');
}

clinicianRouter.get('/me', async (req,res)=>{ try { const token=await auth(req); const c=await requireClinician(token.uid); res.json({uid:token.uid,clinician:serialize(c.clinician)}); } catch(e){sendError(res,e);} });
clinicianRouter.post('/verification', async (req,res)=>{ try { const token=await auth(req); if (!token.uid) throw new ApiError(401,'Sign-in required.'); const {licenseNumber,cadre,facilityId,facilityName}=req.body||{}; if(!String(licenseNumber||'').trim()||!String(cadre||'').trim()) throw new ApiError(400,'License number and cadre are required.'); await adminDb.doc(`users/${token.uid}`).set({role:'CLINICIAN'}, {merge:true}); await adminDb.doc(`clinicians/${token.uid}`).set({uid:token.uid,licenseNumber:String(licenseNumber).trim(),cadre:String(cadre).trim(),facilityId:facilityId||null,facilityName:facilityName||null,verificationStatus:'pending',updatedAt:FieldValue.serverTimestamp()},{merge:true}); res.json({success:true,status:'pending'}); }catch(e){sendError(res,e);} });

clinicianRouter.get('/dashboard', async(req,res)=>{try{const token=await clinician(req); const sessions=await adminDb.collection('clinicianAccessSessions').where('clinicianId','==',token.uid).limit(100).get(); const active=sessions.docs.filter(d=>d.data().status==='active'&&d.data().expiresAt?.toDate?.()>new Date()).length; const expiring=sessions.docs.filter(d=>d.data().status==='active'&&d.data().expiresAt?.toDate?.()<=new Date(Date.now()+120000)).length; const audits=await adminDb.collection('auditEvents').where('actorId','==',token.uid).orderBy('timestamp','desc').limit(20).get().catch(()=>null); res.json({stats:{activeAccessSessions:active,pendingVerificationItems:0,encountersToday:0,alerts:expiring},activity:(audits?.docs||[]).map(d=>document(d.id,d.data()))});}catch(e){sendError(res,e);}});
clinicianRouter.get('/access-sessions', async(req,res)=>{try{const token=await clinician(req); const s=await adminDb.collection('clinicianAccessSessions').where('clinicianId','==',token.uid).limit(100).get(); res.json({items:await Promise.all(s.docs.map(async d=>document(d.id,{...d.data(),motherName:await motherName(String(d.data().motherId))})))});}catch(e){sendError(res,e);}});

clinicianRouter.post('/enter-code', async(req,res)=>{try{const token=await clinician(req); const code=String(req.body?.shareCode||'').replace(/\D/g,'').slice(0,6); if(code.length!==6) throw new ApiError(400,'Enter the 6-digit clinic share code.'); const snap=await adminDb.collection('clinicianAccessSessions').where('shareCode','==',code).where('status','==','active').limit(5).get(); if(snap.empty) throw new ApiError(404,'That code is invalid or has already been used.'); const d=snap.docs.find(x=>!x.data().clinicianId); if(!d) throw new ApiError(409,'That code has already been used.'); const s=d.data(); const expires=s.expiresAt?.toDate?.()||new Date(s.expiresAt); if(expires<=new Date()){await d.ref.update({status:'expired'}); throw new ApiError(410,'That code has expired. Ask the mother to generate a new one.');} res.json({sessionId:d.id,motherId:s.motherId,motherName:await motherName(String(s.motherId)),expiresAt:expires.toISOString(),scope:'Temporary clinical access to the records explicitly covered by this session.'});}catch(e){sendError(res,e);}});
clinicianRouter.post('/sessions/:id/claim', async(req,res)=>{try{const token=await clinician(req); const ref=adminDb.doc(`clinicianAccessSessions/${req.params.id}`); const d=await ref.get(); if(!d.exists) throw new ApiError(404,'Access session not found.'); const s=d.data()!; if(s.clinicianId&&s.clinicianId!==token.uid) throw new ApiError(409,'That code has already been used.'); const expires=s.expiresAt?.toDate?.()||new Date(s.expiresAt); if(s.status!=='active'||expires<=new Date()) throw new ApiError(410,'That code has expired. Ask the mother to generate a new one.'); await ref.update({clinicianId:token.uid}); await logAudit(token.uid,'CLINICIAN','ACCESS_SESSION_STARTED','clinicianAccessSessions',ref.id,s.facilityId||null,s.motherId); res.json({sessionId:ref.id,motherId:s.motherId,motherName:await motherName(String(s.motherId)),expiresAt:expires.toISOString()});}catch(e){sendError(res,e);}});
clinicianRouter.post('/sessions/:id/end', async(req,res)=>{try{const token=await clinician(req); const ref=adminDb.doc(`clinicianAccessSessions/${req.params.id}`); const d=await ref.get(); if(!d.exists||d.data()?.clinicianId!==token.uid) throw new ApiError(403,'Access session not found.'); await ref.update({status:'revoked'}); await logAudit(token.uid,'CLINICIAN','ACCESS_SESSION_ENDED','clinicianAccessSessions',ref.id,null,d.data()?.motherId||null); res.json({success:true});}catch(e){sendError(res,e);}});

clinicianRouter.get('/patients/:motherId/summary', async(req,res)=>{try{const token=await clinician(req); const motherId=req.params.motherId; const session=await requireActiveSession(token.uid,motherId); const records=await getPatientRecords(motherId); await logAudit(token.uid,'CLINICIAN','VIEWED','patientSummary',motherId,null,motherId); res.json({mother:{id:motherId,displayName:await motherName(motherId)},session:serialize(session),records});}catch(e){sendError(res,e);}});
clinicianRouter.get('/patients/:motherId/records/:type', async(req,res)=>{try{const token=await clinician(req); const motherId=req.params.motherId; await requireActiveSession(token.uid,motherId); if(!(CLINICAL_RECORD_GROUPS as readonly string[]).includes(req.params.type)) throw new ApiError(400,'Unsupported clinical record type.'); const q=await adminDb.collectionGroup(req.params.type).where('motherId','==',motherId).limit(200).get(); await logAudit(token.uid,'CLINICIAN','VIEWED',req.params.type,motherId,null,motherId); res.json({items:q.docs.map(d=>document(d.id,d.data()))});}catch(e){sendError(res,e);}});

clinicianRouter.get('/patients/:motherId/verification',async(req,res)=>{try{const token=await clinician(req);const mid=req.params.motherId;await requireActiveSession(token.uid,mid);const records=await getPatientRecords(mid);const pending:any[]=[];for(const [type,items] of Object.entries(records)){if(!Array.isArray(items))continue;(items as any[]).forEach(x=>{if(x.provenance?.status==='REPORTED')pending.push({type,id:x.id,...x});});}await logAudit(token.uid,'CLINICIAN','VIEWED','verificationQueue',mid,null,mid);res.json({items:pending});}catch(e){sendError(res,e);}});
clinicianRouter.post('/verify',async(req,res)=>{try{const token=await clinician(req);const {motherId,recordPath,recordId}=req.body||{};if(!motherId||!recordPath||!recordId)throw new ApiError(400,'motherId, recordPath and recordId are required.');await requireActiveSession(token.uid,motherId);if(recordPath.includes('..')||!/^pregnancies\/[^/]+\/(ancEncounters|newbornRecords|postnatalEncounters|immunizationRecords|growthMeasurements|muacMeasurements|nutritionRecords|developmentRecords)$/.test(recordPath))throw new ApiError(400,'Unsupported clinical record path.');const ref=adminDb.doc(`${recordPath}/${recordId}`);const d=await ref.get();if(!d.exists)throw new ApiError(404,'Record not found.');await ref.update({'provenance.status':'VERIFIED','provenance.verifiedBy':token.uid,'provenance.verifiedAt':FieldValue.serverTimestamp()});await logAudit(token.uid,'CLINICIAN','VERIFIED',recordPath,recordId,null,motherId);res.json({success:true});}catch(e){sendError(res,e);}});
clinicianRouter.post('/encounters',async(req,res)=>{try{const token=await clinician(req);const {motherId,pregnancyId,date,summary}=req.body||{};await requireActiveSession(token.uid,motherId);if(!pregnancyId||!date||!String(summary||'').trim())throw new ApiError(400,'Date and encounter summary are required.');const now=FieldValue.serverTimestamp();const ref=adminDb.collection(`pregnancies/${pregnancyId}/ancEncounters`).doc();await ref.set({motherId,pregnancyId,date,summary:String(summary).trim(),provenance:{status:'VERIFIED',enteredBy:token.uid,verifiedBy:token.uid,enteredAt:now,verifiedAt:now}});await logAudit(token.uid,'CLINICIAN','CREATED','ancEncounters',ref.id,null,motherId);res.json({id:ref.id});}catch(e){sendError(res,e);}});

clinicianRouter.get('/patients/:motherId/notes',async(req,res)=>{try{const token=await clinician(req);const mid=req.params.motherId;await requireActiveSession(token.uid,mid);const q=await adminDb.collection('clinicianPrivateNotes').where('motherId','==',mid).where('clinicianId','==',token.uid).limit(100).get();await logAudit(token.uid,'CLINICIAN','VIEWED','clinicianPrivateNotes',mid,null,mid);res.json({items:q.docs.map(d=>document(d.id,d.data()))});}catch(e){sendError(res,e);}});
clinicianRouter.post('/patients/:motherId/notes',async(req,res)=>{try{const token=await clinician(req);const mid=req.params.motherId;await requireActiveSession(token.uid,mid);const text=String(req.body?.text||'').trim();if(!text)throw new ApiError(400,'Note cannot be empty.');const ref=await adminDb.collection('clinicianPrivateNotes').add({motherId:mid,clinicianId:token.uid,text,createdAt:FieldValue.serverTimestamp()});await logAudit(token.uid,'CLINICIAN','PRIVATE_NOTE_CREATED','clinicianPrivateNotes',ref.id,null,mid);res.json({id:ref.id});}catch(e){sendError(res,e);}});
clinicianRouter.get('/audit',async(req,res)=>{try{const token=await clinician(req);const q=await adminDb.collection('auditEvents').where('actorId','==',token.uid).limit(200).get();res.json({items:q.docs.map(d=>document(d.id,d.data())).sort((a:any,b:any)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')))});}catch(e){sendError(res,e);}});
