export type KepisDose={id:string;vaccine:string;dose:string;weeks:number};
export type KepisScheduleItem=KepisDose&{minimumEligibleDate:string;scheduledDate:string;recommendedActionDate:string};

export const KEPI_SCHEDULE:KepisDose[]=[
{id:'bcg-0',vaccine:'BCG',dose:'Birth',weeks:0},{id:'opv-0',vaccine:'OPV',dose:'Birth',weeks:0},{id:'opv-1',vaccine:'OPV',dose:'1st dose',weeks:6},{id:'penta-1',vaccine:'Penta',dose:'1st dose',weeks:6},{id:'pcv-1',vaccine:'PCV',dose:'1st dose',weeks:6},{id:'rota-1',vaccine:'Rota',dose:'1st dose',weeks:6},{id:'opv-2',vaccine:'OPV',dose:'2nd dose',weeks:10},{id:'penta-2',vaccine:'Penta',dose:'2nd dose',weeks:10},{id:'pcv-2',vaccine:'PCV',dose:'2nd dose',weeks:10},{id:'rota-2',vaccine:'Rota',dose:'2nd dose',weeks:10},{id:'opv-3',vaccine:'OPV',dose:'3rd dose',weeks:14},{id:'penta-3',vaccine:'Penta',dose:'3rd dose',weeks:14},{id:'pcv-3',vaccine:'PCV',dose:'3rd dose',weeks:14},{id:'rota-3',vaccine:'Rota',dose:'3rd dose',weeks:14},{id:'mr-1',vaccine:'MR',dose:'1st dose',weeks:26},{id:'mr-2',vaccine:'MR',dose:'2nd dose',weeks:39},{id:'mr-3',vaccine:'MR',dose:'18 months',weeks:78},{id:'vit-a-1',vaccine:'Vitamin A',dose:'6 months',weeks:26},{id:'vit-a-2',vaccine:'Vitamin A',dose:'12 months',weeks:52},{id:'vit-a-3',vaccine:'Vitamin A',dose:'18 months',weeks:78},{id:'vit-a-4',vaccine:'Vitamin A',dose:'24 months',weeks:104},{id:'vit-a-5',vaccine:'Vitamin A',dose:'30 months',weeks:130},{id:'vit-a-6',vaccine:'Vitamin A',dose:'36 months',weeks:156},{id:'vit-a-7',vaccine:'Vitamin A',dose:'42 months',weeks:182},{id:'vit-a-8',vaccine:'Vitamin A',dose:'48 months',weeks:208},{id:'vit-a-9',vaccine:'Vitamin A',dose:'54 months',weeks:234}];

const addWeeks=(date:string,weeks:number)=>{const d=new Date(`${date}T00:00:00`);d.setDate(d.getDate()+weeks*7);return d.toISOString().slice(0,10)};
export function getKepiSchedule(dob:string,today=new Date()):KepisScheduleItem[]{const todayDate=today.toISOString().slice(0,10);return KEPI_SCHEDULE.map(d=>{const scheduledDate=addWeeks(dob,d.weeks);return {...d,minimumEligibleDate:scheduledDate,scheduledDate,recommendedActionDate:scheduledDate<todayDate?todayDate:scheduledDate}})};
export function getKepiDueItems(dob:string,completed:ReadonlyArray<Pick<KepisDose,'vaccine'|'dose'>>,today=new Date()){const completedKeys=new Set(completed.map(r=>`${r.vaccine}:${r.dose}`));return getKepiSchedule(dob,today).filter(item=>!completedKeys.has(`${item.vaccine}:${item.dose}`));}
