import React, { useState } from 'react';
import { ArrowLeft, AlertCircle, FileText, Save, Stethoscope } from 'lucide-react';
import { AncEncounterDoc, Provenance } from '../../types';
import { auth } from '../../lib/firebase';
import { serverTimestamp } from 'firebase/firestore';
import { useAncMutation } from '../../hooks/useAncMutation';
import ProvenanceBadge from '../ProvenanceBadge';

interface AddAncVisitProps { pregnancyId?: string; onBack: () => void; onSave: (visit: Omit<AncEncounterDoc, 'id'>) => Promise<void>; onSaveDraft?: (draft: Partial<AncEncounterDoc>) => void; }

const input = 'mt-1 min-h-12 w-full rounded-md border border-[#E5E7EB] bg-white px-3 py-2.5 text-sm text-[#1C2833] focus-visible:outline-2 focus-visible:outline-[#5B2C6F]';
const numericInput = `${input} font-mono tabular-nums`;

export const AddAncVisit: React.FC<AddAncVisitProps> = ({ pregnancyId = '', onBack, onSave }) => {
  const [date, setDate] = useState(''); const [facilityName, setFacilityName] = useState(''); const [visitNumber, setVisitNumber] = useState('');
  const [gestationWeeks, setGestationWeeks] = useState(''); const [weight, setWeight] = useState(''); const [systolic, setSystolic] = useState(''); const [diastolic, setDiastolic] = useState('');
  const [fundalHeight, setFundalHeight] = useState(''); const [fetalHeartRate, setFetalHeartRate] = useState(''); const [nextVisitDate, setNextVisitDate] = useState(''); const [notes, setNotes] = useState('');
  const { submit, saving, error, setError } = useAncMutation(onSave); const userId = auth.currentUser?.uid || '';
  const previewProvenance: Provenance = { status: 'REPORTED', enteredBy: userId, enteredAt: new Date().toISOString(), verifiedBy: null, verifiedAt: null };
  const bpHigh = (systolic && Number(systolic) >= 140) || (diastolic && Number(diastolic) >= 90);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); if (!userId) { setError('You must be signed in to save an ANC visit.'); return; }
    const ok = await submit({ pregnancyId, date, facilityName, visitNumber: Number(visitNumber), gestationWeeks: Number(gestationWeeks), weight: Number(weight), systolic: Number(systolic), diastolic: Number(diastolic), fundalHeight: fundalHeight ? Number(fundalHeight) : undefined, fetalHeartRate: fetalHeartRate ? Number(fetalHeartRate) : undefined, nextVisitDate, notes }, { ...previewProvenance, enteredAt: serverTimestamp() as unknown as string }); if (ok) onBack(); };
  return <div className="min-h-screen bg-[#FAFAFC] pb-24 font-clinical"><header className="sticky top-0 z-20 bg-white border-b border-[#E5E7EB] px-4 py-3 flex items-center gap-3"><button onClick={onBack} className="min-h-12 min-w-12 rounded-md bg-[#F5EEF8] border border-[#E5E7EB] text-[#5B2C6F] flex items-center justify-center" aria-label="Back"><ArrowLeft className="w-5 h-5"/></button><div><h1 className="font-bold text-xl text-[#1C2833]">Record ANC contact</h1><p className="text-xs text-[#566573]">Saved as Reported until a clinician verifies the record.</p></div></header>
    <form onSubmit={handleSubmit} className="p-4 space-y-4 max-w-[900px] mx-auto"><section className="bg-white rounded-md border border-[#E5E7EB] shadow-sm p-4 flex items-center justify-between gap-3"><div><p className="font-bold text-sm text-[#1C2833]">Caregiver-reported record</p><p className="text-xs text-[#566573] mt-1">Clinical verification status is preserved with the record.</p></div><ProvenanceBadge provenance={previewProvenance} compact/></section>
      {error&&<div role="alert" className="bg-[#FEF2F2] border border-[#C0392B] rounded-md p-3 text-xs text-[#C0392B] flex gap-2"><AlertCircle className="w-4 h-4 shrink-0"/>{error}</div>}
      <section className="bg-white rounded-md border border-[#E5E7EB] shadow-sm p-5 space-y-4"><h2 className="font-bold text-base text-[#1C2833] flex items-center gap-2"><Stethoscope className="w-4 h-4 text-[#5B2C6F]"/>Visit information</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><label className="text-xs font-semibold text-[#566573]">Visit date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className={numericInput} required/></label><label className="text-xs font-semibold text-[#566573]">ANC contact<select value={visitNumber} onChange={e=>setVisitNumber(e.target.value)} className={input} required><option value="">Select contact</option>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>Contact {n}</option>)}</select></label></div><label className="block text-xs font-semibold text-[#566573]">Health facility<input value={facilityName} onChange={e=>setFacilityName(e.target.value)} placeholder="Enter facility name" className={input} required/></label><label className="block text-xs font-semibold text-[#566573]">Gestational age (weeks)<input type="number" min="1" max="43" value={gestationWeeks} onChange={e=>setGestationWeeks(e.target.value)} placeholder="Enter weeks" className={numericInput} required/></label></section>
      <section className="bg-white rounded-md border border-[#E5E7EB] shadow-sm p-5 space-y-4"><h2 className="font-bold text-base text-[#1C2833] flex items-center gap-2"><FileText className="w-4 h-4 text-[#5B2C6F]"/>Maternal measurements</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><label className="text-xs font-semibold text-[#566573]">Weight (kg)<input type="number" step="0.1" min="1" value={weight} onChange={e=>setWeight(e.target.value)} placeholder="Enter value" className={numericInput} required/></label><label className="text-xs font-semibold text-[#566573]">Blood pressure (mmHg)<div className="flex gap-2 mt-1"><input aria-label="Systolic blood pressure" type="number" value={systolic} onChange={e=>setSystolic(e.target.value)} placeholder="Systolic" className={`${numericInput} mt-0 ${bpHigh?'border-[#C0392B] bg-[#FEF2F2]':''}`} required/><input aria-label="Diastolic blood pressure" type="number" value={diastolic} onChange={e=>setDiastolic(e.target.value)} placeholder="Diastolic" className={`${numericInput} mt-0 ${bpHigh?'border-[#C0392B] bg-[#FEF2F2]':''}`} required/></div>{bpHigh&&<span role="alert" className="mt-1 block text-xs font-semibold text-[#C0392B]">Clinical alert: blood pressure is at or above 140/90 mmHg.</span>}</label></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><label className="text-xs font-semibold text-[#566573]">Fundal height (cm)<input type="number" step="0.1" value={fundalHeight} onChange={e=>setFundalHeight(e.target.value)} placeholder="Optional" className={numericInput}/></label><label className="text-xs font-semibold text-[#566573]">Fetal heart rate (bpm)<input type="number" value={fetalHeartRate} onChange={e=>setFetalHeartRate(e.target.value)} placeholder="Optional" className={numericInput}/></label></div><label className="block text-xs font-semibold text-[#566573]">Next visit date<input type="date" value={nextVisitDate} onChange={e=>setNextVisitDate(e.target.value)} className={numericInput}/></label></section>
      <section className="bg-white rounded-md border border-[#E5E7EB] shadow-sm p-5"><label className="block text-xs font-semibold text-[#1C2833]">Mother's notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} placeholder="Optional notes or questions for your clinician" className="mt-1 min-h-24 w-full rounded-md border border-[#E5E7EB] bg-white p-3 text-sm resize-none focus-visible:outline-2 focus-visible:outline-[#5B2C6F]"/></label></section>
      <div className="flex flex-col sm:flex-row gap-2"><button disabled={saving} className="min-h-12 flex-1 rounded-md bg-[#5B2C6F] px-5 py-3 text-white font-bold hover:bg-[#4A235A] disabled:opacity-50"><Save className="inline w-4 h-4 mr-2"/>{saving?'Saving…':'Record ANC contact'}</button><button type="button" onClick={onBack} className="min-h-12 rounded-md bg-white border border-[#E5E7EB] px-5 py-3 text-[#5B2C6F] font-bold">Cancel</button></div>
    </form></div>;
};
