import React from 'react';
import { ArrowLeft, CheckCircle2, Clock, Share2, Calendar, MapPin } from 'lucide-react';
import { AncEncounterDoc } from '../../types';

interface AncVisitDetailProps { visit?: Partial<AncEncounterDoc> | null; onBack: () => void; onShareWithClinician?: () => void; }

type EncounterWithNextVisit = Partial<AncEncounterDoc> & { nextVisitDate?: string };

export const AncVisitDetail: React.FC<AncVisitDetailProps> = ({ visit, onBack, onShareWithClinician }) => {
  if (!visit) return <div className="min-h-screen bg-lavender-50 p-5"><button onClick={onBack} className="w-10 h-10 rounded-full bg-white border border-border-hairline text-haven-deep flex items-center justify-center"><ArrowLeft className="w-5 h-5" /></button><p className="mt-8 font-body text-sm text-ink-600">No ANC visit selected.</p></div>;
  const record = visit as EncounterWithNextVisit;
  const provenance = record.provenance;
  const verified = provenance?.status === 'VERIFIED';
  const enteredDate = provenance?.enteredAt ? new Date(provenance.enteredAt).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}) : null;
  const verifiedDate = provenance?.verifiedAt ? new Date(provenance.verifiedAt).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}) : null;

  return <div className="min-h-screen bg-lavender-50 pb-24"><header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-border-hairline px-4 py-3.5 flex items-center gap-3"><button onClick={onBack} className="w-10 h-10 rounded-full bg-lavender-100 border border-border-hairline text-haven-deep flex items-center justify-center"><ArrowLeft className="w-5 h-5" /></button><div><h1 className="font-display font-bold text-xl text-ink-900">ANC visit {record.visitNumber || ''}</h1><p className="font-body text-xs text-ink-600">{record.date ? new Date(record.date).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}) : 'Date not recorded'}</p></div></header>
    <main className="p-4 space-y-4 max-w-[420px] mx-auto"><section className="bg-white rounded-[20px] border border-border-hairline shadow-card-1 p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-display font-bold text-sm text-ink-900">{record.facilityName || 'Facility not recorded'}</p><p className="font-body text-xs text-ink-600 mt-1">{provenance?.enteredBy ? `Entered by account · ${enteredDate || 'date not recorded'}` : 'Entry provenance not recorded'}</p></div><span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-pill text-xs font-display font-bold ${verified ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' : 'bg-lavender-100 text-haven-deep border border-haven-orchid/20'}`}>{verified ? <CheckCircle2 className="w-3.5 h-3.5" /> : <Clock className="w-3.5 h-3.5" />}{verified ? 'Verified' : 'Reported'}</span></div><div className="h-px bg-border-hairline my-4" /><div className="space-y-3">{[['Weight',record.weight ? `${record.weight} kg` : null],['Blood pressure',record.bloodPressure],['Fundal height',record.fundalHeight ? `${record.fundalHeight} cm` : null],['Fetal heart rate',record.fetalHeartRate ? `${record.fetalHeartRate} bpm` : null],['Next visit',record.nextVisitDate ? new Date(record.nextVisitDate).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}) : null]].map(([label,value])=><div key={label as string} className="flex items-center justify-between gap-4"><span className="font-body text-sm text-ink-600">{label}</span><span className="font-display font-bold text-sm text-ink-900">{value || 'Not recorded'}</span></div>)}</div></section>
      <section className="bg-white rounded-[20px] border border-border-hairline shadow-card-1 p-5 space-y-3"><div className="flex items-center gap-2"><MapPin className="w-4 h-4 text-haven-orchid" /><span className="font-display font-bold text-sm text-ink-900">Provenance</span></div>{verified ? <p className="font-body text-xs text-ink-600">Verified by {provenance?.clinicianName || provenance?.verifiedBy || 'clinician'}{verifiedDate ? ` · ${verifiedDate}` : ''}. The original entry remains traceable.</p> : <p className="font-body text-xs text-ink-600">This record was reported by the mother and has not been clinically verified yet.</p>}{provenance?.facilityName && <p className="font-body text-xs text-ink-600">Recorded facility: {provenance.facilityName}</p>}</section>
      {record.notes && <section className="bg-white rounded-[20px] border border-border-hairline shadow-card-1 p-5"><p className="font-display font-bold text-sm text-ink-900">Mother's notes</p><p className="font-body text-sm text-ink-700 mt-2 leading-relaxed">{record.notes}</p></section>}
      {onShareWithClinician && <button onClick={onShareWithClinician} className="w-full py-3.5 rounded-pill bg-white border-[1.5px] border-haven-deep text-haven-deep font-display font-bold"><Share2 className="inline w-4 h-4 mr-2" />Share with clinician</button>}
    </main></div>;
};