import React,{useEffect,useMemo,useState} from 'react';
import {addDoc,collection,onSnapshot,orderBy,query,serverTimestamp} from 'firebase/firestore';
import {AlertTriangle,ArrowLeft,CheckCircle2,Clock,MessageCircle,Send,ShieldCheck,Sparkles,X} from 'lucide-react';
import {auth,db} from '../../lib/firebase';
import EmptyState from '../EmptyState';
import {HavenMessageDoc,HavenSessionDoc} from '../../types';
import {classifyLayerOneOffline,refreshSafetyPatternCache} from '../../lib/safetyPatternCache';

interface Props{isOpen:boolean;onClose:()=>void;onSendToChat?:(query:string)=>void}
type View='home'|'session'|'suggested'|'privacy'|'clinical'|'emergency';
type EmergencyKind='physical_danger'|'self_harm_or_violence';
type Classification='safe'|'medication_request'|'sensitive_topic'|'insufficient_info';
const assistant='bg-[#EEE7F8] text-[#241451]';
const staticSuggested=['What should I eat today?','Is this normal?','What’s coming up this week?'];
const offlineCopy="Haven needs an internet connection — try again when you're back online";

export const AskHavenSheet:React.FC<Props>=({isOpen,onClose,onSendToChat})=>{
 const[view,setView]=useState<View>('home'); const[sessions,setSessions]=useState<Array<HavenSessionDoc&{lastMessagePreview?:string;updatedAt?:any}>>([]); const[sessionsLoading,setSessionsLoading]=useState(true); const[messages,setMessages]=useState<Array<HavenMessageDoc&{suggestedFollowups?:string[];classification?:Classification}>>([]); const[sessionId,setSessionId]=useState<string|null>(null); const[input,setInput]=useState(''); const[pendingMessage,setPendingMessage]=useState(''); const[loading,setLoading]=useState(false); const[error,setError]=useState(''); const[online,setOnline]=useState(typeof navigator==='undefined'?true:navigator.onLine); const[emergencyKind,setEmergencyKind]=useState<EmergencyKind>('physical_danger');
 useEffect(()=>{const onlineHandler=()=>setOnline(true),offlineHandler=()=>setOnline(false);window.addEventListener('online',onlineHandler);window.addEventListener('offline',offlineHandler);return()=>{window.removeEventListener('online',onlineHandler);window.removeEventListener('offline',offlineHandler)}},[]);
 useEffect(()=>{if(!isOpen||!online)return;void refreshSafetyPatternCache().catch(()=>{});},[isOpen,online]);
 useEffect(()=>{if(!isOpen)return;const uid=auth.currentUser?.uid;if(!uid){setSessions([]);setSessionsLoading(false);return}setSessionsLoading(true);const un=onSnapshot(query(collection(db,'havenSessions'),orderBy('updatedAt','desc')),snap=>{setSessions(snap.docs.map(d=>({id:d.id,...d.data()} as HavenSessionDoc&{lastMessagePreview?:string;updatedAt?:any})).filter(s=>s.userId===uid));setSessionsLoading(false)},()=>setSessionsLoading(false));return()=>un()},[isOpen]);
 useEffect(()=>{if(!sessionId)return;return onSnapshot(query(collection(db,'havenSessions',sessionId,'messages'),orderBy('createdAt','asc')),snap=>setMessages(snap.docs.map(d=>({id:d.id,...d.data()} as any))))},[sessionId]);
 const followups=useMemo(()=>{for(let i=messages.length-1;i>=0;i--){if(messages[i].role==='assistant'&&messages[i].suggestedFollowups?.length)return messages[i].suggestedFollowups!}return[]},[messages]);
 if(!isOpen)return null;
 const openExisting=(id:string)=>{setSessionId(id);setView('session');setError('')};
 const start=async(initial?:string)=>{const uid=auth.currentUser?.uid;if(!uid)return;setError('');const r=await addDoc(collection(db,'havenSessions'),{userId:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setSessionId(r.id);setMessages([]);setView('session');if(initial)void send(initial,r.id)};
 const send=async(raw=input,sid=sessionId)=>{const text=raw.trim();if(!text||!sid||!auth.currentUser||loading)return;setInput('');setError('');const localLayer=classifyLayerOneOffline(text);if(localLayer){setEmergencyKind(localLayer);setPendingMessage('');setView('emergency');return}if(!online){setError(offlineCopy);return}setLoading(true);try{const token=await auth.currentUser.getIdToken();const response=await fetch('/api/v1/chat',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({sessionId:sid,message:text})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Haven could not respond right now.');if(data.classification==='emergency'){setEmergencyKind(data.handoff==='self_harm_or_violence'?'self_harm_or_violence':'physical_danger');setPendingMessage('');setView('emergency');return}if(data.classification==='sensitive_topic'){setPendingMessage(text);setView('privacy');return}if(data.classification==='medication_request'){setView('clinical');return}if(data.classification==='insufficient_info'||data.classification==='safe'){onSendToChat?.(text)}else throw new Error('Haven returned an unsupported response.')}catch(e:any){setError(e.message||'Haven could not respond right now.')}finally{setLoading(false)}};
 const content=view==='home'?<>
  <header className="flex flex-col items-center text-center pt-1 pb-4"><div className="w-14 h-14 rounded-md flex items-center justify-center mb-3 bg-[#33178A]"><Sparkles className="w-6 h-6 text-white" strokeWidth={2}/></div><h1 className="font-display font-bold text-[20px] text-ink-900">Ask Haven</h1><p className="font-body text-[13px] text-ink-600 mt-1">Guidance for pregnancy, your child, and what’s next.</p></header>
  <button onClick={()=>start()} className="w-full font-display font-semibold text-[15px] text-white rounded-md py-3.5 mb-4 bg-[#33178A] shadow-sm">Start a new conversation</button>
  <div className="mb-5"><p className="font-body text-[11px] font-semibold uppercase tracking-wide text-ink-600 mb-2">Suggested questions</p><div className="flex flex-wrap gap-2">{staticSuggested.map(q=><button key={q} onClick={()=>start(q)} className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs text-[#241451]">{q}</button>)}</div></div>
  <p className="font-body text-[11px] font-semibold uppercase tracking-wide text-ink-600 mb-2">Past conversations</p>{sessionsLoading?<div className="h-16 rounded-md bg-slate-100 animate-pulse"/>:sessions.length===0?<EmptyState icon={Sparkles} title="No conversations yet" message="Once you ask Haven something, you’ll be able to find it here again."/>:<div className="space-y-3">{sessions.map(s=><button key={s.id} onClick={()=>openExisting(s.id)} className="w-full text-left bg-white rounded-md p-[16px] shadow-sm border border-slate-200"><div className="flex gap-3 items-center"><MessageCircle className="w-5 h-5 text-[#6C3EAC] shrink-0"/><div className="min-w-0 flex-1"><p className="font-body font-semibold text-[14px] text-ink-900 truncate">{s.lastMessagePreview||'Conversation'}</p><p className="font-body text-[12px] text-ink-600 mt-0.5">{formatRelativeDate(s.updatedAt||s.createdAt)}</p></div><ArrowLeft className="w-4 h-4 rotate-180 text-slate-400"/></div></button>)}</div>}
 </>:view==='suggested'?<><Header title="Suggested questions" back={()=>setView('home')} onClose={onClose}/><div className="space-y-2">{[...staticSuggested,'How can I prepare for my next visit?','What should I pack for birth?'].map(q=><button key={q} onClick={()=>start(q)} className="w-full rounded-md border border-slate-200 bg-white p-4 text-left text-sm">{q}</button>)}</div></>:view==='privacy'?<><Header title="Before you continue" back={()=>setView('session')} onClose={onClose}/><div className="rounded-md bg-white p-5 border border-slate-200 shadow-sm"><ShieldCheck className="h-7 w-7 text-[#33178A]"/><h2 className="mt-3 font-display text-xl font-bold">This is a sensitive topic</h2><p className="mt-2 text-sm leading-6 text-slate-600">Haven can discuss sensitive subjects without judgment. This message will be sent to Haven only after you acknowledge this reminder.</p></div><button disabled={loading||!online} onClick={()=>{setView('session');void send(pendingMessage,sessionId||undefined)}} className="w-full rounded-md py-3.5 font-display font-bold text-white disabled:opacity-40 bg-[#33178A]">Continue</button><button onClick={()=>{setPendingMessage('');setInput('');setView('session')}} className="w-full rounded-md border border-[#33178A] py-3.5 font-display font-bold text-[#33178A]">Don’t send this</button></>:view==='clinical'?<><Header title="Clinical safety" back={()=>setView('session')} onClose={onClose}/><div className="rounded-md bg-amber-50 border border-amber-200 p-5"><AlertTriangle className="h-7 w-7 text-amber-700"/><h2 className="mt-3 font-display text-2xl font-bold">Let’s keep medication questions with a clinician</h2><p className="mt-2 text-sm leading-6 text-slate-600">Haven can help you prepare questions, but it won’t provide a medication dose or prescribing instruction.</p></div><button onClick={onClose} className="w-full rounded-md py-4 font-display font-bold text-white bg-[#33178A]">Find a facility</button></>:view==='emergency'?<><Header title="Please get help now" back={()=>setView('session')} onClose={onClose}/><div className="rounded-md bg-red-50 border border-red-200 p-5"><AlertTriangle className="h-7 w-7 text-red-700"/><h2 className="mt-3 font-display text-2xl font-bold">Emergency support is needed</h2>{emergencyKind==='self_harm_or_violence'?<p className="mt-2 text-sm leading-6 text-slate-600">Please contact a trusted person and use a verified local crisis resource now.</p>:<p className="mt-2 text-sm leading-6 text-slate-600">The symptoms you described need prompt in-person attention. Use MomHaven’s emergency pathway rather than waiting for a chat response.</p>}</div><button onClick={()=>{window.dispatchEvent(new Event('mom-haven-open-emergency'));onClose()}} className="w-full rounded-md py-4 font-display font-bold text-white bg-red-700">Go to Emergency</button></>:<>
  <Header title="Haven" back={()=>setView('home')} onClose={onClose}/><div className="flex items-center gap-2 text-xs text-green-700"><CheckCircle2 className="h-4 w-4"/>Grounded in your saved MomHaven context</div>{!online&&<div className="mt-3 rounded-md bg-[#F0EBFA] px-3 py-2 text-xs text-slate-600 flex gap-2"><Clock className="h-4 w-4"/>{offlineCopy}</div>}{error&&<div className="mt-3 rounded-md bg-red-50 border border-red-200 px-3 py-2 text-xs text-red-700">{error}</div>}<div className="mt-3 space-y-3 min-h-[260px]">{messages.map(m=><div key={m.id} className={m.role==='assistant'?'flex items-end gap-2':'flex justify-end'}>{m.role==='assistant'&&<div className="h-7 w-7 rounded-md flex items-center justify-center text-white bg-[#33178A]"><Sparkles className="h-3.5 w-3.5"/></div>}<div className={'max-w-[82%] rounded-md px-4 py-3 text-sm leading-5 '+(m.role==='assistant'?assistant:'text-white')} style={m.role==='user'?{background:'#33178A'}:undefined}>{m.text}</div></div>)}{loading&&<div className="flex items-center gap-2 text-xs text-slate-600">Reviewing MOH triage guidelines for reported symptoms…</div>}</div>{followups.length>0&&<div className="flex flex-wrap gap-2">{followups.map(q=><button key={q} disabled={loading||!online} onClick={()=>void send(q)} className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs disabled:opacity-50">{q}</button>)}</div>}<div className="mt-3 flex gap-2 rounded-md border border-slate-200 bg-white p-2 shadow-sm"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} disabled={loading||!online} placeholder={online?'Message Haven…':'Haven is offline'} className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none disabled:opacity-50"/><button disabled={loading||!online||!input.trim()} onClick={()=>void send()} className="h-10 w-10 shrink-0 rounded-md flex items-center justify-center text-white disabled:opacity-40 bg-[#33178A]"><Send className="h-4 w-4"/></button></div><div className="mt-3 rounded-md bg-slate-100 px-3 py-2 text-xs text-slate-600 flex gap-2"><Clock className="h-4 w-4"/>For severe symptoms, use Emergency instead of waiting for chat.</div></>;
 return <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4"><button className="absolute inset-0 bg-slate-900/60" onClick={onClose}/><section className="relative z-10 w-full max-w-[430px] max-h-[92vh] overflow-y-auto rounded-t-md sm:rounded-md bg-slate-50 p-5 shadow-sm"><div className="mx-auto mb-4 h-1.5 w-12 rounded-md bg-slate-300"/>{content}</section></div>;
};
function Header({title,back,onClose}:{title:string;back:()=>void;onClose:()=>void}){return <div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><button onClick={back} className="h-9 w-9 rounded-md bg-white border border-slate-200 flex items-center justify-center"><ArrowLeft className="h-4 w-4"/></button><h2 className="font-display text-lg font-bold">{title}</h2></div><button onClick={onClose} className="h-9 w-9 rounded-md bg-white border border-slate-200 flex items-center justify-center"><X className="h-4 w-4"/></button></div>}
function formatRelativeDate(value:any){const date=value?.toDate?value.toDate():new Date(value);if(Number.isNaN(date.getTime()))return 'Saved conversation';const diff=Date.now()-date.getTime();const mins=Math.floor(diff/60000);if(mins<1)return 'Just now';if(mins<60)return `${mins}m ago`;const hours=Math.floor(mins/60);if(hours<24)return `${hours}h ago`;const days=Math.floor(hours/24);if(days<7)return `${days}d ago`;return date.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
