import React, { useEffect, useState } from 'react';
import { Baby, Syringe, Scale, Smile, ChevronRight, ChevronDown, Heart } from 'lucide-react';
import { collection, doc, onSnapshot, updateDoc } from 'firebase/firestore';
import { auth, db } from '../../lib/firebase';
import { ChildDoc } from '../../types';
import EmptyState from '../EmptyState';

interface ChildDashboardProps { child?: ChildDoc | null; childrenList?: ChildDoc[]; onSwitchChild: () => void; onOpenNewbornRecord: () => void; onOpenPncOverview: () => void; onOpenImmunization: () => void; onOpenGrowth: () => void; onOpenDevelopment: () => void; onOpenTimeline: () => void; }
const getAgeText = (dob: string) => { const birth = new Date(`${dob}T00:00:00`), now = new Date(); let months = (now.getFullYear() - birth.getFullYear()) * 12 + (now.getMonth() - birth.getMonth()); if (now.getDate() < birth.getDate()) months -= 1; months = Math.max(0, months); if (months === 0) { const days = Math.max(0, Math.floor((now.getTime() - birth.getTime()) / 86400000)); return `${days} day${days === 1 ? '' : 's'} old`; } if (months < 24) return `${months} month${months === 1 ? '' : 's'} old`; const years = Math.floor(months / 12), remainder = months % 12; return remainder ? `${years}y ${remainder}m old` : `${years} year${years === 1 ? '' : 's'} old`; };

export const ChildDashboard: React.FC<ChildDashboardProps> = ({ child, childrenList = [], onSwitchChild, onOpenNewbornRecord, onOpenPncOverview, onOpenImmunization, onOpenGrowth, onOpenDevelopment, onOpenTimeline }) => {
  const [nameDraft, setNameDraft] = useState(''); const [savingName, setSavingName] = useState(false); const [nameError, setNameError] = useState(''); const [counts, setCounts] = useState({ immunization: 0, growth: 0, development: 0 });
  useEffect(() => { setNameDraft(child?.name || ''); setNameError(''); }, [child?.id, child?.name]);
  useEffect(() => { if (!child?.id) { setCounts({ immunization: 0, growth: 0, development: 0 }); return; } const mappings = [['immunizationRecords', 'immunization'], ['growthMeasurements', 'growth'], ['developmentRecords', 'development']] as const; const unsubs = mappings.map(([subcollection, key]) => onSnapshot(collection(db, 'children', child.id, subcollection), (snapshot) => setCounts((current) => ({ ...current, [key]: snapshot.size })), (error) => console.error(`Could not load ${subcollection}:`, error))); return () => unsubs.forEach((unsubscribe) => unsubscribe()); }, [child?.id]);
  if (!child) return <div className="min-h-screen bg-surface-canvas p-5"><EmptyState icon={Baby} title="No child record selected" message="Add a child from the Journey tab before opening a child dashboard." /></div>;
  const isUnnamed = !child.name; const sex = child.sex === 'boy' ? 'Boy' : 'Girl'; const dob = new Date(`${child.dateOfBirth}T00:00:00`).toLocaleDateString('en-KE', { day: 'numeric', month: 'short', year: 'numeric' });
  const statuses = [{ label: 'Immunization', count: counts.immunization, icon: Syringe, action: onOpenImmunization }, { label: 'Growth', count: counts.growth, icon: Scale, action: onOpenGrowth }, { label: 'Development', count: counts.development, icon: Smile, action: onOpenDevelopment }];
  const areas = [{ label: 'Newborn record', detail: 'Birth and immediate newborn record', icon: Baby, action: onOpenNewbornRecord }, { label: 'Postnatal care', detail: 'Recorded postnatal contacts', icon: Heart, action: onOpenPncOverview }, { label: 'Immunization', detail: 'Vaccination records and schedule', icon: Syringe, action: onOpenImmunization }, { label: 'Growth & nutrition', detail: 'Growth measurements and nutrition', icon: Scale, action: onOpenGrowth }, { label: 'Development', detail: 'Developmental milestones', icon: Smile, action: onOpenDevelopment }];
  const saveName = async (event: React.FormEvent) => { event.preventDefault(); const name = nameDraft.trim(), uid = auth.currentUser?.uid; if (!name || !uid || !child.id) return; setSavingName(true); setNameError(''); try { await updateDoc(doc(db, 'children', child.id), { name }); } catch (error) { console.error('Could not save child name:', error); setNameError('We could not save the name. Please try again.'); } finally { setSavingName(false); } };

  return <div className="min-h-screen bg-surface-canvas pb-24">
    <header className="sticky top-0 z-20 flex items-center justify-between border-b border-border-light bg-white px-4 py-3.5"><div><h1 className="font-consumer text-2xl font-bold text-text-primary">{child.name || 'Child record'}</h1><p className="font-clinical text-xs text-text-muted">Child health journey</p></div>{childrenList.length > 1 && <button onClick={onSwitchChild} className="flex min-h-[48px] items-center gap-1.5 rounded-md border border-border-light bg-brand-surface px-3 text-xs font-bold text-brand-primary">Switch child <ChevronDown className="h-3.5 w-3.5" /></button>}</header>
    <main className="mx-auto max-w-lg space-y-4 p-4">
      {isUnnamed && <section className="rounded-xl border border-brand-primary/30 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-clinical text-[11px] font-semibold uppercase tracking-[0.08em] text-brand-primary">One quick step</p><h2 className="mt-1 font-consumer text-xl font-bold text-text-primary">What’s your baby’s name?</h2><p className="mt-1 font-clinical text-sm text-text-muted">Give this child record a name so it is easy to recognise later.</p></div><Baby className="h-7 w-7 shrink-0 text-brand-primary" /></div><form onSubmit={saveName} className="mt-4 flex gap-2"><input autoFocus value={nameDraft} onChange={(e) => setNameDraft(e.target.value)} className="min-w-0 flex-1 rounded-md border border-border-light bg-surface-canvas p-3 font-clinical text-sm text-text-primary" placeholder="Child's name" aria-label="Child's name" /><button disabled={savingName || !nameDraft.trim()} className="rounded-md bg-brand-primary px-4 font-consumer font-bold text-white disabled:opacity-50">{savingName ? 'Saving…' : 'Save name'}</button></form>{nameError && <p className="mt-2 font-clinical text-xs text-clinical-danger">{nameError}</p>}</section>}
      <section className="rounded-2xl border border-border-light bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-md bg-brand-surface"><Baby className="h-8 w-8 text-brand-primary" /></div><div><h2 className="font-consumer text-2xl font-bold text-text-primary">{getAgeText(child.dateOfBirth)}</h2><p className="font-clinical text-xs text-text-muted">Born <span className="font-mono">{dob}</span> · {sex}</p></div></div></section>
      <div className="grid grid-cols-3 gap-2.5">{statuses.map(({ label, count, icon: Icon, action }) => <button key={label} onClick={action} className="rounded-xl border border-border-light bg-white p-3 text-center shadow-sm"><Icon className="mx-auto mb-2 h-5 w-5 text-brand-primary" /><span className="block font-consumer text-xs font-bold text-text-primary">{count ? `${count} recorded` : 'Not started'}</span><span className="font-clinical text-[10px] text-text-muted">{label}</span></button>)}</div>
      <div className="space-y-2.5"><p className="px-1 font-consumer text-sm font-bold text-text-primary">Care areas</p>{areas.map(({ label, detail, icon: Icon, action }) => <button key={label} onClick={action} className="flex w-full items-center gap-3 rounded-xl border border-border-light bg-white p-4 text-left shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-md bg-brand-surface"><Icon className="h-5 w-5 text-brand-primary" /></div><span className="flex-1"><b className="font-consumer text-sm font-bold text-text-primary">{label}</b><span className="mt-0.5 block font-clinical text-xs text-text-muted">{detail}</span></span><ChevronRight className="h-4 w-4 text-text-muted" /></button>)}</div>
      <button onClick={onOpenTimeline} className="w-full rounded-md border border-brand-primary bg-white py-3.5 font-consumer font-bold text-brand-primary">View first-five-years timeline</button>
    </main>
  </div>;
};
