import React,{useEffect,useMemo,useState} from 'react';
import {ChevronLeft,Users,Shield,Clock,Trash2,CheckCircle2,History} from 'lucide-react';
import {collection,onSnapshot,query,where,doc,updateDoc} from 'firebase/firestore';
import {auth,db} from '../../lib/firebase';
import {RevokeAccessModal} from './RevokeAccessModal';
interface ConnectedAccessProps{onBack:()=>void}
type AccessRow={id:string;kind:'Partner'|'Clinician';status:string;name:string;createdAt?:string;expiresAt?:string;sharedSections?:string[]};
const fmt=(v?:string)=>v?new Date(v).toLocaleString([], {day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}):'—';
export const ConnectedAccess:React.FC<ConnectedAccessProps>=({onBack})=>{
 const[partners,setPartners]=useState<any[]|null>(null);const[clinicians,setClinicians]=useState<any[]|null>(null);const[revokeTarget,setRevokeTarget]=useState<AccessRow|null>(null);
 useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid)return;const a=onSnapshot(query(collection(db,'partnerRelationships'),where('motherId','==',uid)),s=>setPartners(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setPartners([]));const b=onSnapshot(query(collection(db,'clinicianAccessSessions'),where('motherId','==',uid)),s=>setClinicians(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setClinicians([]));return()=>{a();b()}},[]);
 useEffect(()=>{if(!clinicians)return;const now=Date.now();clinicians.filter(c=>c.status==='active'&&new Date(c.expiresAt).getTime()<=now).forEach(c=>void updateDoc(doc(db,'clinicianAccessSessions',c.id),{status:'expired'}).catch(()=>undefined));},[clinicians]);
 const rows=useMemo<AccessRow[]>(()=>[...(partners||[]).map(p=>({id:p.id,kind:'Partner' as const,status:p.status,name:p.partnerName||'Connected partner',createdAt:p.createdAt,sharedSections:p.sharedSections})),...(clinicians||[]).map(c=>({id:c.id,kind:'Clinician' as const,status:c.status,name:'Clinician access session',createdAt:c.createdAt,expiresAt:c.expiresAt}))].sort((a,b)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()),[partners,clinicians]);
 const loading=partners===null||clinicians===null;const active=rows.filter(r=>r.status==='active');const history=rows.filter(r=>r.status!=='active');
 const confirmRevoke=async()=>{if(!revokeTarget)return;const path=revokeTarget.kind==='Partner'?'partnerRelationships':'clinicianAccessSessions';await updateDoc(doc(db,path,revokeTarget.id),{status:'revoked',revokedAt:new Date().toISOString()});setRevokeTarget(null)};
 const badge=(status:string)=><span className={`px-2.5 py-1 rounded-pill text-[10px] font-display font-bold capitalize flex items-center gap-1 ${status==='active'?'bg-emerald-100 text-emerald-800':'bg-lavender-100 text-ink-600'}`}>{status==='active'&&<CheckCircle2 className="w-3 h-3"/>}{status}</span>;
 const card=(r:AccessRow)=><div key={`${r.kind}-${r.id}`} className="bg-white rounded-[20px] border border-border-hairline shadow-card-1 p-4 space-y-3"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${r.kind==='Partner'?'bg-emerald-100 text-emerald-700':'bg-lavender-100 text-haven-orchid'}`}>{r.kind==='Partner'?<Users className="w-5 h-5"/>:<Shield className="w-5 h-5"/>}</div><div><h4 className="font-display font-bold text-sm text-ink-900">{r.name}</h4><p className="font-body text-xs text-ink-600">{r.kind} · {r.createdAt?`connected since ${fmt(r.createdAt)}`:'date unavailable'}</p></div></div>{badge(r.status)}</div>{r.kind==='Partner'&&r.sharedSections?.length?<p className="font-body text-xs text-ink-600 bg-lavender-50 p-2.5 rounded-xl">Shared: {r.sharedSections.join(', ')}</p>:null}{r.kind==='Clinician'&&r.status==='active'&&r.expiresAt?<p className="font-body text-xs text-ink-600 flex items-center gap-1.5"><Clock className="w-3.5 h-3.5"/>Expires {fmt(r.expiresAt)}</p>:null}{r.kind==='Clinician'&&r.status!=='active'&&r.expiresAt?<p className="font-body text-xs text-ink-600 flex items-center gap-1.5"><History className="w-3.5 h-3.5"/>{r.status==='expired'?'Expired':'Revoked'} {fmt(r.expiresAt)}</p>:null}{r.status==='active'&&<button onClick={()=>setRevokeTarget(r)} className="w-full py-2.5 rounded-pill border border-red-200 text-red-600 font-display font-bold text-xs flex items-center justify-center gap-1.5"><Trash2 className="w-3.5 h-3.5"/>Revoke access</button>}</div>;
 return <div className="space-y-6 pb-12 animate-fade-in"><div className="flex items-center justify-between"><button onClick={onBack} className="w-10 h-10 rounded-full bg-white border border-border-hairline shadow-sm flex items-center justify-center"><ChevronLeft className="w-5 h-5"/></button><h1 className="font-display font-bold text-xl text-ink-900">Connected Access</h1><div className="w-10"/></div><div className="bg-lavender-50 border border-lavender-200 rounded-[20px] p-4"><p className="font-display font-bold text-sm text-haven-deep">Everyone with access, in one place</p><p className="font-body text-xs text-ink-600 mt-1 leading-relaxed">Partner connections can remain active. Clinician access is temporary and expires automatically.</p></div><section className="space-y-3"><span className="font-body text-[11px] font-bold tracking-wider text-ink-600 uppercase px-1">ACTIVE ACCESS</span>{loading?<div className="h-28 rounded-[20px] bg-lavender-100 animate-pulse"/>:active.length?active.map(card):<div className="bg-white rounded-[20px] border border-border-hairline p-6 text-center"><Shield className="w-8 h-8 mx-auto text-haven-orchid mb-2"/><p className="font-display font-bold text-sm text-ink-900">No active access</p><p className="font-body text-xs text-ink-600 mt-1">No partner or clinician currently has access.</p></div>}</section><section className="space-y-3"><span className="font-body text-[11px] font-bold tracking-wider text-ink-600 uppercase px-1">ACCESS HISTORY</span>{loading?<div className="h-20 rounded-[20px] bg-lavender-100 animate-pulse"/>:history.length?history.map(card):<div className="bg-white rounded-[20px] border border-border-hairline p-5 text-sm text-ink-600">No previous access sessions yet.</div>}</section>{revokeTarget&&<RevokeAccessModal isOpen targetName={revokeTarget.name} onClose={()=>setRevokeTarget(null)} onConfirm={confirmRevoke}/>}</div>;
};
