import React, { useState } from 'react';
import { ChevronLeft, AlertTriangle, PhoneCall, Flame, ThermometerSnowflake, Wind, Droplets, Activity, HeartCrack, WifiOff, Building2, ShieldAlert } from 'lucide-react';

interface NewbornDangerSignsProps { onBack: () => void; onOpenEmergency: () => void; facilityPhone?: string; facilityName?: string; }
interface DangerSignItem { id: string; title: string; plainDescription: string; actionInstruction: string; icon: React.ReactNode; }

export const NewbornDangerSigns: React.FC<NewbornDangerSignsProps> = ({ onBack, onOpenEmergency, facilityPhone, facilityName }) => {
  const [checkedSigns, setCheckedSigns] = useState<Record<string, boolean>>({});
  const dangerSignsList: DangerSignItem[] = [
    { id: 'feeding', title: 'Unable to feed or suckle at breast', plainDescription: 'Baby is completely refusing to feed or too weak to suckle at the breast.', actionInstruction: 'Seek medical care immediately.', icon: <HeartCrack className="w-5 h-5 text-red-600" /> },
    { id: 'convulsions', title: 'Convulsions or fits', plainDescription: 'Repeated spasms, abnormal eye movements, or rhythmic jerking of the limbs.', actionInstruction: 'Keep the airway clear and seek hospital care immediately.', icon: <Activity className="w-5 h-5 text-red-600" /> },
    { id: 'breathing', title: 'Fast or difficult breathing', plainDescription: 'Very fast breathing, grunting, or the lower chest pulling in deeply when breathing.', actionInstruction: 'Seek medical care immediately.', icon: <Wind className="w-5 h-5 text-red-600" /> },
    { id: 'fever', title: 'Baby feels very hot', plainDescription: 'The baby feels unusually hot or a thermometer shows a high temperature.', actionInstruction: 'Do not delay seeking medical care.', icon: <Flame className="w-5 h-5 text-red-600" /> },
    { id: 'hypothermia', title: 'Baby feels unusually cold', plainDescription: 'The baby feels cold, especially the hands, feet or body.', actionInstruction: 'Keep the baby warm and seek medical care urgently.', icon: <ThermometerSnowflake className="w-5 h-5 text-blue-600" /> },
    { id: 'jaundice', title: 'Yellow skin or yellow eyes very early', plainDescription: 'Yellowing that appears during the first day of life needs urgent assessment.', actionInstruction: 'Seek medical care urgently.', icon: <AlertTriangle className="w-5 h-5 text-amber-600" /> },
    { id: 'cord', title: 'Red, swollen, bleeding or smelly cord', plainDescription: 'The skin around the cord is red or swollen, or there is pus, bleeding or a bad smell.', actionInstruction: 'Seek medical care urgently.', icon: <Droplets className="w-5 h-5 text-red-600" /> },
    { id: 'lethargy', title: 'Very sleepy, floppy or unconscious', plainDescription: 'Baby is unusually difficult to wake, very floppy, or does not respond normally.', actionInstruction: 'Treat this as an emergency and go for care immediately.', icon: <ShieldAlert className="w-5 h-5 text-red-600" /> },
  ];
  const selectedCount = Object.values(checkedSigns).filter(Boolean).length;
  return <div className="min-h-screen bg-lavender-50 flex flex-col pb-24">
    <header className="sticky top-0 bg-white/95 backdrop-blur-md border-b border-border-hairline px-4 py-3.5 z-20 flex items-center justify-between"><button onClick={onBack} className="w-9 h-9 rounded-full bg-lavender-100 flex items-center justify-center text-haven-deep"><ChevronLeft className="w-5 h-5" /></button><div className="text-center"><h1 className="font-display font-bold text-lg text-ink-900">Newborn Danger Signs</h1><p className="font-body text-[11px] text-ink-600">Clear guidance for the first 28 days</p></div><div className="w-9" /></header>
    <main className="p-4 space-y-4 max-w-lg mx-auto w-full">
      <div className="p-3 rounded-2xl bg-lavender-100 border border-border-hairline flex items-center gap-2 text-haven-deep"><WifiOff className="w-4 h-4 text-haven-orchid" /><span className="font-display font-semibold text-xs">Available offline</span><span className="font-body text-[11px] text-ink-600 ml-auto">Guidance stays on this screen</span></div>
      <div className="p-4 rounded-[20px] bg-red-600 text-white shadow-card-1"><div className="flex items-start gap-2.5"><AlertTriangle className="w-6 h-6 flex-shrink-0" /><div><h2 className="font-display font-bold text-base">One danger sign is enough to seek urgent care</h2><p className="font-body text-xs text-white/90 mt-1">Do not wait for several symptoms to appear.</p></div></div></div>
      <div className="space-y-2.5"><div className="flex items-center justify-between px-1"><span className="font-display font-bold text-xs uppercase tracking-wider text-ink-600">Danger signs</span>{selectedCount > 0 && <span className="font-display font-bold text-xs text-red-600 px-2 py-0.5 rounded-full bg-red-100">{selectedCount} checked</span>}</div>
        {dangerSignsList.map(sign => { const checked = !!checkedSigns[sign.id]; return <button type="button" key={sign.id} onClick={()=>setCheckedSigns(prev=>({...prev,[sign.id]:!prev[sign.id]}))} className={`w-full text-left p-4 rounded-[20px] border shadow-card-1 transition-all ${checked ? 'bg-red-50 border-red-500 ring-1 ring-red-500' : 'bg-white border-border-hairline'}`}><div className="flex items-start gap-3"><div className={`w-10 h-10 rounded-2xl flex items-center justify-center flex-shrink-0 ${checked ? 'bg-red-100' : 'bg-lavender-50'}`}>{sign.icon}</div><div className="flex-1"><div className="flex items-start justify-between gap-2"><h3 className="font-display font-bold text-sm text-ink-900">{sign.title}</h3><span className={`w-5 h-5 rounded border-2 flex-shrink-0 ${checked ? 'bg-red-600 border-red-600' : 'bg-white border-border-hairline'}`} aria-hidden="true" /></div><p className="font-body text-xs text-ink-700 mt-1 leading-relaxed">{sign.plainDescription}</p><p className="font-body text-[11px] text-red-600 font-semibold mt-2">Action: <span className="font-normal text-ink-600">{sign.actionInstruction}</span></p></div></div></button>; })}
      </div>
      <div className="space-y-2.5 pt-1"><button onClick={onOpenEmergency} className="w-full py-4 px-6 rounded-pill bg-gradient-to-r from-red-700 to-red-600 text-white font-display font-bold text-base flex items-center justify-center gap-2.5"><PhoneCall className="w-5 h-5" />Go to Emergency now</button>{facilityPhone ? <a href={`tel:${facilityPhone}`} className="w-full py-3 px-6 rounded-pill bg-white border-[1.5px] border-haven-deep text-haven-deep font-display font-semibold text-sm flex items-center justify-center gap-2"><Building2 className="w-4 h-4 text-haven-orchid" />Call {facilityName || 'your facility'}</a> : <button type="button" disabled className="w-full py-3 px-6 rounded-pill bg-white border-[1.5px] border-border-hairline text-ink-600 font-display font-semibold text-sm flex items-center justify-center gap-2 opacity-70"><Building2 className="w-4 h-4" />Facility phone not recorded</button>}</div>
    </main>
  </div>;
};

export default NewbornDangerSigns;
