import React,{useEffect,useState} from 'react';
import {Copy,RefreshCw,Check,X} from 'lucide-react';
import {doc,getDoc,setDoc,collection,query,where,getDocs,serverTimestamp} from 'firebase/firestore';
import {auth,db} from '../../lib/firebase';
interface Props{isOpen:boolean;onClose:()=>void}
export const PartnerConnectionCodeSheet:React.FC<Props>=({isOpen,onClose})=>{const[code,setCode]=useState('');const[copied,setCopied]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const generate=async()=>{const uid=auth.currentUser?.uid;if(!uid)return;setBusy(true);setError('');try{let candidate='';let exists=true;while(exists){candidate=String(Math.floor(100000+Math.random()*900000));const snap=await getDocs(query(collection(db,'partnerRelationships'),where('code','==',candidate),where('status','==','pending')));exists=!snap.empty}const profile=await getDoc(doc(db,'motherProfiles',uid));const user=await getDoc(doc(db,'users',uid));const motherName=profile.data()?.fullName||user.data()?.displayName||'the mother';await setDoc(doc(db,'partnerRelationships',candidate),{motherId:uid,partnerId:null,code:candidate,status:'pending',motherName,createdAt:serverTimestamp()});
   const pregnancies=await getDocs(query(collection(db,'pregnancies'),where('motherId','==',uid),where('status','==','active')));const p=pregnancies.docs[0]?.data();if(p?.birthPlan)await setDoc(doc(db,'partnerShares',uid),{motherName,birthPlan:p.birthPlan,updatedAt:serverTimestamp()},{merge:true});else await setDoc(doc(db,'partnerShares',uid),{motherName,updatedAt:serverTimestamp()},{merge:true});setCode(candidate);
 }catch(e){console.error(e);setError('Could not generate a connection code. Please try again.')}finally{setBusy(false)}};
 useEffect(()=>{if(isOpen){setCode('');setCopied(false);generate()}},[isOpen]);if(!isOpen)return null;return <div className="fixed inset-0 z-50 bg-black/50 flex items-end justify-center"><div className="bg-white rounded-t-[28px] w-full max-w-md p-6 space-y-5 shadow-2xl"><div className="w-12 h-1.5 bg-lavender-200 rounded-full mx-auto"/><div className="flex items-center justify-between"><h3 className="font-display font-bold text-xl text-ink-900">Partner connection code</h3><button onClick={onClose} className="w-8 h-8 rounded-full bg-lavender-100 flex items-center justify-center"><X className="w-4 h-4"/></button></div><p className="font-body text-xs text-ink-600">Share this 6-digit code with your partner. It can be used once and then becomes inactive.</p><div className="bg-lavender-50 border border-lavender-200 rounded-[20px] p-6 text-center"><h2 className="font-display font-bold text-4xl text-haven-deep tracking-[0.18em] font-mono">{busy?'••••••':code}</h2>{error&&<p className="text-xs text-red-600 mt-2">{error}</p>}</div><button onClick={()=>{navigator.clipboard?.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1500)}} disabled={!code||busy} className="w-full py-4 rounded-pill bg-gradient-to-r from-haven-deep to-haven-orchid text-white font-display font-bold flex items-center justify-center gap-2">{copied?<Check/>:<Copy/>}{copied?'Code copied':'Copy/share code'}</button><button onClick={generate} disabled={busy} className="w-full py-3 rounded-pill border border-haven-deep text-haven-deep font-display font-bold flex items-center justify-center gap-2"><RefreshCw className="w-4 h-4"/>Generate new code</button></div></div>};
