import React from 'react';
import { ArrowLeft, Calendar, ChevronRight, Plus, ShieldCheck, Stethoscope, CheckCircle2, Circle } from 'lucide-react';
import { PregnancyDoc, AncEncounterDoc, MotherProfileDoc } from '../../types';
import { PREGNANCY_WEEKS } from '../../data/pregnancyWeeks';

interface PregnancyOverviewProps { pregnancy?: PregnancyDoc|null; motherProfile?:MotherProfileDoc|null; encounters?:AncEncounterDoc[]; birthPlan?:{id?:string}|null; onBack:()=>void; onOpenAddVisit:()=>void; onOpenTimeline:()=>void; onOpenAncOverview:()=>void; onOpenHealthHistory:()=>void; onOpenBirthPlan:()=>void; onOpenBirthOutcome:()=>void; }
const getWeek=(p?:PregnancyDoc|null)=>p?.gestationalAgeWeeks ?? (p?.lmp?Math.max(1,Math.floor((Date.now()-new Date(p.lmp).getTime())/(7*24*60*60*1000))+1):null);
const formatDate=(v?:string)=>v?new Date(`${v.slice(0,10)}T00:00:00`).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}):'Not recorded';

export const PregnancyOverview:React.FC<PregnancyOverviewProps>=({pregnancy,motherProfile,encounters=[],onBack,onOpenAddVisit,onOpenTimeline,onOpenAncOverview,onOpenHealthHistory,onOpenBirthPlan,onOpenBirthOutcome})=>{
 const week=getWeek(pregnancy); const edd=pregnancy?.edd||pregnancy?.estimatedDeliveryDate; const weekInfo=week?PREGNANCY_WEEKS[week]:null;
 if(!pregnancy)return <div className="min-h-screen bg-surface-canvas p-5"><button onClick={onBack} className="flex h-12 w-12 items-center justify-center rounded-md border border-border-light bg-white text-brand-primary" aria-label="Back"><ArrowLeft className="h-5 w-5"/></button><div className="mt-10 rounded-xl border border-border-light bg-white p-6 text-center shadow-sm"><h1 className="font-consumer text-xl font-bold text-text-primary">No pregnancy recorded</h1><p className="mt-1 font-clinical text-sm text-text-muted">Add a pregnancy before viewing this journey.</p></div></div>;
 return <div className="min-h-screen bg-surface-canvas pb-24">
  <header className="sticky top-0 z-20 flex items-center gap-3 border-b border-border-light bg-white px-4 py-3.5"><button onClick={onBack} className="flex h-12 w-12 min-h-0 items-center justify-center rounded-md border border-border-light bg-white text-brand-primary" aria-label="Back"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="font-consumer text-xl font-bold text-text-primary">Pregnancy overview</h1><p className="font-clinical text-xs text-text-muted">{week?`Week ${week}`:'Gestation not recorded'} · EDD {formatDate(edd)}</p></div></header>
  <main className="mx-auto max-w-[420px] space-y-4 p-4">
   <section className="rounded-2xl border border-border-light bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="font-clinical text-[11px] font-semibold uppercase tracking-wide text-text-muted">Current pregnancy</p><h2 className="mt-1 font-consumer text-4xl font-bold text-text-primary">{week?`Week ${week}`:'—'}</h2><p className="mt-1 font-clinical text-xs text-text-muted">EDD · <span className="font-mono">{formatDate(edd)}</span></p></div><div className="rounded-md bg-brand-surface px-3 py-2 font-mono text-xs font-bold text-brand-primary">{week?`${Math.round((week/40)*100)}%`:'—'}</div></div>{week&&<div className="mt-5"><div className="h-2 overflow-hidden rounded-md bg-slate-100"><div className="h-full bg-brand-accent" style={{width:`${Math.min(100,(week/40)*100)}%`}}/></div><div className="mt-2 flex justify-between font-mono text-[10px] text-text-muted"><span>01</span><span>40</span></div></div>}{weekInfo&&<p className="mt-4 border-t border-border-light pt-4 font-clinical text-sm leading-6 text-text-muted">{weekInfo.sizeFact}</p>}</section>

   <section className="grid grid-cols-2 gap-3">{[
    ['EDD',formatDate(edd)],['Gravida',motherProfile?.gravida!=null?String(motherProfile.gravida):'Not recorded'],['Parity',motherProfile?.parity!=null?String(motherProfile.parity):motherProfile?.para!=null?String(motherProfile.para):'Not recorded'],['Blood group',motherProfile?.bloodGroup||'Not recorded']
   ].map(([label,value])=><div key={label} className="rounded-xl border border-border-light bg-white p-4 shadow-sm"><p className="font-clinical text-[11px] font-semibold uppercase tracking-wide text-text-muted">{label}</p><p className="mt-1 font-mono text-sm font-bold text-text-primary">{value}</p></div>)}</section>

   <section className="rounded-xl border border-border-light bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-consumer text-base font-bold text-text-primary">ANC contact ledger</h2><p className="font-clinical text-xs text-text-muted">Eight contacts across the pregnancy journey</p></div><span className="font-mono text-xs font-bold text-brand-primary">{encounters.length}/8</span></div><div className="space-y-2">{Array.from({length:8},(_,i)=>{const n=i+1;const encounter=encounters.find(e=>e.visitNumber===n);return <div key={n} className="flex items-center gap-3 rounded-md border border-border-light p-3"><div className="shrink-0">{encounter?<CheckCircle2 className="h-5 w-5 text-clinical-normal"/>:<Circle className="h-5 w-5 text-brand-primary"/>}</div><div className="min-w-0 flex-1"><p className="font-clinical text-sm font-semibold text-text-primary">ANC Contact <span className="font-mono">{n}</span></p><p className="font-clinical text-xs text-text-muted">{encounter?`${formatDate(encounter.date)}${encounter.facilityName?` · ${encounter.facilityName}`:''}`:'Not recorded'}</p>{encounter?.bloodPressure&&<p className="font-mono text-xs text-text-muted">BP {encounter.bloodPressure}{encounter.weight!=null?` · ${encounter.weight} kg`:''}</p>}</div>{!encounter&&<button onClick={onOpenAddVisit} className="min-h-0 rounded-md border border-brand-primary px-3 py-2 font-consumer text-xs font-bold text-brand-primary">Record contact</button>}</div>})}</div></section>

   <div className="space-y-2.5"><button onClick={onOpenAddVisit} className="flex w-full items-center justify-center gap-2 rounded-md bg-brand-primary py-3.5 font-consumer font-bold text-white"><Plus className="h-4 w-4"/>Record ANC contact</button><button onClick={onOpenBirthPlan} className="flex w-full items-center justify-center gap-2 rounded-md border border-brand-primary bg-white py-3 font-consumer font-bold text-brand-primary"><ShieldCheck className="h-4 w-4"/>View birth plan</button><button onClick={onOpenBirthOutcome} className="w-full rounded-md border border-clinical-danger bg-white py-3 font-consumer font-bold text-clinical-danger">Record childbirth outcome</button></div>
   <div className="space-y-2"><button onClick={onOpenTimeline} className="flex w-full items-center gap-3 rounded-xl border border-border-light bg-white p-4 text-left shadow-sm"><Calendar className="h-5 w-5 text-brand-primary"/><span className="flex-1"><b className="font-consumer text-sm text-text-primary">Pregnancy timeline</b><span className="block font-clinical text-xs text-text-muted">Milestones, trimesters and recorded contacts</span></span><ChevronRight className="h-4 w-4 text-text-muted"/></button><button onClick={onOpenAncOverview} className="flex w-full items-center gap-3 rounded-xl border border-border-light bg-white p-4 text-left shadow-sm"><Stethoscope className="h-5 w-5 text-brand-primary"/><span className="flex-1"><b className="font-consumer text-sm text-text-primary">ANC records</b><span className="block font-clinical text-xs text-text-muted">{encounters.length} recorded contact{encounters.length===1?'':'s'}</span></span><ChevronRight className="h-4 w-4 text-text-muted"/></button></div>
  </main>
 </div>;
};
