import React,{useEffect,useRef,useState} from 'react';
import {PhoneAuthProvider,PhoneMultiFactorGenerator,multiFactor,MultiFactorResolver,MultiFactorInfo,RecaptchaVerifier,signInWithEmailAndPassword,signInWithPopup,User,UserCredential} from 'firebase/auth';
import {auth,googleProvider} from '../lib/firebase';
import {ShieldCheck,ArrowLeft,Loader2} from 'lucide-react';
interface Props{onSuccess?:()=>void}
export default function AdminAuth({onSuccess}:Props){const[step,setStep]=useState<'signin'|'enroll'|'verify'>('signin');const[email,setEmail]=useState('');const[pw,setPw]=useState('');const[code,setCode]=useState('');const[phone,setPhone]=useState('');const[verificationId,setVerificationId]=useState('');const[resolver,setResolver]=useState<MultiFactorResolver|null>(null);const[hint,setHint]=useState('your enrolled phone');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const recaptcha=useRef<RecaptchaVerifier|null>(null);
 const getRecaptcha=()=>{if(!recaptcha.current)recaptcha.current=new RecaptchaVerifier(auth,'admin-recaptcha',{size:'invisible'});return recaptcha.current};
 useEffect(()=>()=>{recaptcha.current?.clear();recaptcha.current=null},[]);
 const ensureAdmin=async(u:User)=>{const snap=await import('firebase/firestore').then(({doc,getDoc})=>getDoc(doc((requireFirebaseDb as any),'users',u.uid)));if(!snap.exists()||snap.data()?.role!=='ADMIN'){await auth.signOut();throw new Error('Admin access required.')}};
 const startMfaChallenge=async(r:MultiFactorResolver)=>{setResolver(r);const firstHint=r.hints.find((x:MultiFactorInfo)=>x.factorId===PhoneMultiFactorGenerator.FACTOR_ID);setHint((firstHint as any)?.phoneNumber||'your enrolled phone');setBusy(true);setError('');try{if(!firstHint)throw new Error('No supported administrator two-factor method is enrolled.');const provider=new PhoneAuthProvider(auth);const id=await provider.verifyPhoneNumber({multiFactorHint:firstHint,session:r.session},getRecaptcha());setVerificationId(id);setStep('verify')}catch(e:any){setError(e?.message||'Unable to send the verification code.')}finally{setBusy(false)}};
 const signIn=async(fn:()=>Promise<UserCredential>)=>{setBusy(true);setError('');try{const cred=await fn();await ensureAdmin(cred.user);onSuccess?.()}catch(e:any){if(e?.code==='auth/multi-factor-auth-required'){await startMfaChallenge(e.resolver)}else setError(e?.message||'Unable to sign in.')}finally{setBusy(false)}};
 const confirm=async()=>{if(!resolver||!verificationId||code.length!==6)return;setBusy(true);try{const cred=PhoneAuthProvider.credential(verificationId,code);await (await import('firebase/auth')).multiFactor(resolver as any);await auth.signInWithCredential?.(cred as any);onSuccess?.()}catch(e:any){setError(e?.message||'That code is invalid or expired.')}finally{setBusy(false)}};
 const body=<div className="min-h-screen bg-[#F7F3FC] flex items-center justify-center p-4"><div className="w-full max-w-md bg-white rounded-[28px] shadow-[0_24px_70px_rgba(51,23,138,.15)] p-7"><div className="w-14 h-14 rounded-2xl bg-[#EEE7F8] flex items-center justify-center text-[#33178A]"><ShieldCheck/></div><h1 className="mt-5 font-display text-2xl font-bold">Admin verification</h1><p className="mt-2 text-sm text-[#6D6380]">Platform operations only. Clinical records are not available to Admin.</p>{step==='signin'&&<div className="mt-6 space-y-3"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full rounded-xl border border-[#E5DFF0] px-4 py-3"/><input value={pw} onChange={e=>setPw(e.target.value)} type="password" placeholder="Password" className="w-full rounded-xl border border-[#E5DFF0] px-4 py-3"/>{error&&<p className="text-xs text-[#C4283C]">{error}</p>}<button disabled={busy} onClick={()=>void signIn(()=>signInWithEmailAndPassword(auth,email,pw))} className="w-full rounded-full bg-[#33178A] text-white py-3 font-display font-bold">{busy?'Signing in…':'Sign in'}</button><button onClick={()=>void signIn(()=>signInWithPopup(auth,googleProvider))} className="w-full rounded-full border border-[#33178A] py-3 font-display font-bold text-[#33178A]">Continue with Google</button></div>}{step==='verify'&&<div className="mt-6 space-y-3"><p className="text-sm">Enter the code sent to {hint}.</p><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="123456" className="w-full rounded-xl border border-[#E5DFF0] px-4 py-4 text-center text-2xl tracking-widest"/>{error&&<p className="text-xs text-[#C4283C]">{error}</p>}<button disabled={busy||code.length!==6} onClick={()=>void confirm()} className="w-full rounded-full bg-[#33178A] text-white py-3 font-display font-bold">{busy?'Checking…':'Verify'}</button><button onClick={()=>{setStep('signin');setResolver(null)}} className="w-full py-2 text-sm text-[#33178A]">Back to sign in</button></div>}<div id="admin-recaptcha"/></div></div>;
 return body;
}
const requireFirebaseDb:any=null;
