import React,{useEffect,useState} from 'react';
import {Lock,Delete,ShieldCheck} from 'lucide-react';
import {auth} from '../lib/firebase';
import {hashPin,verifyLegacyPin,verifyPin} from '../lib/pinSecurity';
const TIMEOUT_MS=5*60*1000;
export const AppLockGate:React.FC<{children:React.ReactNode}>=({children})=>{
 const[locked,setLocked]=useState(false);const[pin,setPin]=useState('');const[error,setError]=useState('');
 const lock=()=>{const isAppLockConfigured=Boolean(localStorage.getItem('momHaven.appLock.pinHash'));if(isAppLockConfigured){localStorage.setItem('momHaven.appLock.locked','true');setLocked(true);setPin('');setError('')}};
 useEffect(()=>{const isAppLockConfigured=Boolean(localStorage.getItem('momHaven.appLock.pinHash'));if(isAppLockConfigured){localStorage.setItem('momHaven.appLock.locked','true');setLocked(true)};const onVisibility=()=>{if(document.visibilityState==='hidden')lock();};document.addEventListener('visibilitychange',onVisibility);const timer=window.setInterval(()=>{const at=Number(localStorage.getItem('momHaven.appLock.lastUnlockAt')||0);if(at&&Date.now()-at>=TIMEOUT_MS)lock()},15000);return()=>{document.removeEventListener('visibilitychange',onVisibility);window.clearInterval(timer)}},[]);
 useEffect(()=>{if(!auth.currentUser){setLocked(false);return;}if(localStorage.getItem('momHaven.appLock.locked')==='true')setLocked(true)},[auth.currentUser]);
 const digit=(d:string)=>{if(pin.length>=4)return;const next=pin+d;setPin(next);setError('');if(next.length===4){const salt=localStorage.getItem('momHaven.appLock.pinSalt');const expected=localStorage.getItem('momHaven.appLock.pinHash');void(async()=>{try{let valid=salt&&expected?await verifyPin(next,expected,salt):false;if(!valid&&salt&&expected&&!expected.startsWith('pbkdf2-sha256-')){valid=await verifyLegacyPin(next,expected,salt);if(valid){const upgraded=await hashPin(next,salt);localStorage.setItem('momHaven.appLock.pinHash',upgraded.hash);}}if(valid){localStorage.setItem('momHaven.appLock.locked','false');localStorage.setItem('momHaven.appLock.lastUnlockAt',String(Date.now()));setLocked(false);setPin('')}else{setError('Incorrect PIN.');setPin('')}}catch{setError('Unable to verify PIN.');setPin('')}})()}};
 if(!locked)return <>{children}</>;
 return <div className="fixed inset-0 z-[100] bg-slate-50 flex items-center justify-center p-5" role="dialog" aria-modal="true" aria-labelledby="app-lock-title"><div className="w-full max-w-sm bg-white rounded-md border border-slate-200 shadow-sm p-7 text-center"><div className="w-16 h-16 rounded-md bg-[#F0EBFA] text-[#33178A] flex items-center justify-center mx-auto"><Lock className="w-8 h-8" aria-hidden="true"/></div><h1 id="app-lock-title" className="mt-5 font-display font-bold text-2xl text-slate-900">MomHaven is locked</h1><p className="mt-2 font-body text-sm text-slate-600">Enter your App Lock PIN to continue. The PIN is stored locally as a salted password-derived hash.</p><div className="mt-5 flex justify-center gap-4" aria-label={`${pin.length} of 4 digits entered`}>{[0,1,2,3].map(i=><span key={i} aria-hidden="true" className={`w-4 h-4 rounded-full ${pin.length>i?'bg-[#33178A]':'bg-slate-200'}`}/>)}</div>{error&&<p className="mt-3 text-xs font-display font-bold text-red-700" role="alert">{error}</p>}<div className="mt-6 grid grid-cols-3 gap-3 max-w-[270px] mx-auto">{['1','2','3','4','5','6','7','8','9'].map(d=><button type="button" aria-label={`Enter ${d}`} key={d} onClick={()=>digit(d)} className="h-14 rounded-md bg-[#F0EBFA] text-[#33178A] font-display font-bold text-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-700">{d}</button>)}<button type="button" onClick={()=>setPin('')} className="h-14 rounded-md border border-slate-200 text-slate-600 font-display font-bold text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-700">Clear</button><button type="button" aria-label="Enter 0" onClick={()=>digit('0')} className="h-14 rounded-md bg-[#F0EBFA] text-[#33178A] font-display font-bold text-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-700">0</button><button type="button" aria-label="Delete last digit" onClick={()=>setPin(p=>p.slice(0,-1))} className="h-14 rounded-md border border-slate-200 text-slate-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-700"><Delete className="w-5 h-5 mx-auto" aria-hidden="true"/></button></div><div className="mt-5 flex items-center justify-center gap-1.5 text-[11px] text-slate-600"><ShieldCheck className="w-3.5 h-3.5 text-[#33178A]" aria-hidden="true"/>Local device protection · not clinician sharing</div></div></div>;
};
