import React,{useEffect,useState} from 'react';
import {Lock,Delete,ShieldCheck} from 'lucide-react';
import {auth} from '../lib/firebase';
const hashPin=async(pin:string,salt:string)=>{const bytes=new TextEncoder().encode(`mom-haven-app-lock-v2:${salt}:${pin}`);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')};
const TIMEOUT_MS=5*60*1000;
export const AppLockGate:React.FC<{children:React.ReactNode}>=({children})=>{
 const[locked,setLocked]=useState(false);const[pin,setPin]=useState('');const[error,setError]=useState('');
 const lock=()=>{if(localStorage.getItem('momHaven.appLock.pinHash')){localStorage.setItem('momHaven.appLock.locked','true');setLocked(true);setPin('');setError('')}};
 useEffect(()=>{if(localStorage.getItem('momHaven.appLock.pinHash')){localStorage.setItem('momHaven.appLock.locked','true');setLocked(true)};const onVisibility=()=>{if(document.visibilityState==='hidden')lock();};document.addEventListener('visibilitychange',onVisibility);const timer=window.setInterval(()=>{const at=Number(localStorage.getItem('momHaven.appLock.lastUnlockAt')||0);if(at&&Date.now()-at>=TIMEOUT_MS)lock()},15000);return()=>{document.removeEventListener('visibilitychange',onVisibility);window.clearInterval(timer)}},[]);
 useEffect(()=>{if(!auth.currentUser) {setLocked(false);return;}if(localStorage.getItem('momHaven.appLock.locked')==='true')setLocked(true)},[auth.currentUser]);
 const digit=(d:string)=>{if(pin.length>=4)return;const next=pin+d;setPin(next);setError('');if(next.length===4){const salt=localStorage.getItem('momHaven.appLock.pinSalt');const expected=localStorage.getItem('momHaven.appLock.pinHash');void (async()=>{const actual=salt&&expected?await hashPin(next,salt):'';if(actual===expected){localStorage.setItem('momHaven.appLock.locked','false');localStorage.setItem('momHaven.appLock.lastUnlockAt',String(Date.now()));setLocked(false);setPin('')}else{setError('Incorrect PIN.');setPin('')}})()}};
 if(!locked)return <>{children}</>;
 return <div className="fixed inset-0 z-[100] bg-[#F7F3FC] flex items-center justify-center p-5"><div className="w-full max-w-sm bg-white rounded-[28px] border border-[#E5DFF0] shadow-2xl p-7 text-center"><div className="w-16 h-16 rounded-2xl bg-[#EEE7F8] text-[#33178A] flex items-center justify-center mx-auto"><Lock className="w-8 h-8"/></div><h1 className="mt-5 font-display font-bold text-2xl text-[#241451]">MomHaven is locked</h1><p className="mt-2 font-body text-sm text-[#6D6380]">Enter your App Lock PIN to continue. This PIN stays on this device.</p><div className="mt-5 flex justify-center gap-4">{[0,1,2,3].map(i=><span key={i} className={`w-4 h-4 rounded-full ${pin.length>i?'bg-[#33178A]':'bg-[#E5DFF0]'}`}/>)}</div>{error&&<p className="mt-3 text-xs font-display font-bold text-red-600">{error}</p>}<div className="mt-6 grid grid-cols-3 gap-3 max-w-[270px] mx-auto">{['1','2','3','4','5','6','7','8','9'].map(d=><button key={d} onClick={()=>digit(d)} className="h-14 rounded-2xl bg-[#F7F3FC] text-[#33178A] font-display font-bold text-xl">{d}</button>)}<button onClick={()=>setPin('')} className="h-14 rounded-2xl border border-[#E5DFF0] text-[#6D6380] font-display font-bold text-xs">Clear</button><button onClick={()=>digit('0')} className="h-14 rounded-2xl bg-[#F7F3FC] text-[#33178A] font-display font-bold text-xl">0</button><button onClick={()=>setPin(p=>p.slice(0,-1))} className="h-14 rounded-2xl border border-[#E5DFF0] text-[#6D6380]"><Delete className="w-5 h-5 mx-auto"/></button></div><div className="mt-5 flex items-center justify-center gap-1.5 text-[11px] text-[#6D6380]"><ShieldCheck className="w-3.5 h-3.5 text-[#33178A]"/>Local device protection · not clinician sharing</div></div></div>;
};
