import React, { useState } from 'react';
import { LayoutDashboard, KeyRound, Stethoscope, ClipboardList, LogOut } from 'lucide-react';
import EmptyState from './EmptyState';

type ClinicianTab = 'dashboard' | 'access' | 'workspace' | 'audit';
interface ClinicianShellProps { clinicianId?: string; clinicianName?: string; facilityName?: string; onSignOut?: () => void; }
const tabs: { id: ClinicianTab; label: string; icon: React.ElementType }[] = [{ id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'access', label: 'Patient Access', icon: KeyRound }, { id: 'workspace', label: 'Workspace', icon: Stethoscope }, { id: 'audit', label: 'Audit', icon: ClipboardList }];

export default function ClinicianShell({ clinicianName, facilityName, onSignOut }: ClinicianShellProps) {
  const [activeTab, setActiveTab] = useState<ClinicianTab>('dashboard'); const current = tabs.find(t => t.id === activeTab) || tabs[0]; const Icon = current.icon;
  return <div className="min-h-screen bg-[var(--lavender-50)] pb-20"><header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-[var(--border-hairline)] px-4 py-3 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider font-display font-bold text-[var(--haven-orchid)]">MomHaven Clinical</p><h1 className="font-display font-extrabold text-lg">{clinicianName || 'Clinician Portal'}</h1>{facilityName && <p className="text-[11px] text-[var(--ink-500)]">{facilityName}</p>}</div>{onSignOut && <button type="button" onClick={onSignOut} aria-label="Sign out" className="w-9 h-9 rounded-full bg-[var(--lavender-50)] flex items-center justify-center cursor-pointer"><LogOut className="w-4 h-4" /></button>}</header><main className="max-w-3xl mx-auto p-4"><div className="bg-white rounded-2xl border border-[var(--border-hairline)] shadow-card-1 overflow-hidden"><EmptyState icon={Icon} title={`No ${current.label.toLowerCase()} data yet`} message="Clinical records, patient connections, encounters, verification events, and audit entries will appear here only when they exist in the live clinical data source. No demo patient or clinician activity is preloaded." /></div></main><nav className="fixed bottom-0 left-0 right-0 z-20 bg-white border-t border-[var(--border-hairline)]"><div className="max-w-3xl mx-auto h-16 flex items-center justify-around">{tabs.map(tab => { const TabIcon = tab.icon; return <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl cursor-pointer ${activeTab === tab.id ? 'text-[var(--haven-deep)]' : 'text-[var(--ink-400)]'}`}><TabIcon className="w-5 h-5" /><span className="text-[10px] font-display font-bold">{tab.label}</span></button>; })}</div></nav></div>;
}
