import React, { useState, useEffect } from 'react';
import { Timer, Share2, Copy, Check, ShieldCheck, X, RefreshCw } from 'lucide-react';
import { AccessibleModal } from './AccessibleModal';
interface ClinicShareModalProps { isOpen:boolean; onClose:()=>void; motherName?:string }
export const ClinicShareModal:React.FC<ClinicShareModalProps>=({isOpen,onClose,motherName='Faith Chemutai'})=>{
 const[shareCode,setShareCode]=useState('784-219'); const[secondsRemaining,setSecondsRemaining]=useState(894); const[copied,setCopied]=useState(false);
 useEffect(()=>{if(!isOpen)return;const interval=setInterval(()=>setSecondsRemaining(prev=>prev>0?prev-1:0),1000);return()=>clearInterval(interval)},[isOpen]);
 if(!isOpen)return null; const minutes=Math.floor(secondsRemaining/60);const seconds=secondsRemaining%60;const timeFormatted=`${minutes}:${seconds<10?'0':''}${seconds}`;
 const handleCopy=()=>{navigator.clipboard?.writeText?.(shareCode.replace('-',''));setCopied(true);setTimeout(()=>setCopied(false),2000)};
 const handleRegenerate=()=>{setShareCode(`${Math.floor(100+Math.random()*900)}-${Math.floor(100+Math.random()*900)}`);setSecondsRemaining(900)};
 return <AccessibleModal isOpen={isOpen} onClose={onClose} titleId="clinic-share-title" title="Clinic Share Code"><div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50"><div className="relative w-full max-w-md bg-white rounded-md shadow-sm border border-slate-200 overflow-hidden p-6"><div className="flex items-center justify-between pb-4 border-b border-slate-200"><div className="flex items-center gap-2.5"><div className="w-9 h-9 rounded-md bg-slate-50 border border-slate-200 flex items-center justify-center text-[#33178A]"><Share2 className="w-5 h-5" aria-hidden="true"/></div><div><h2 id="clinic-share-title" className="text-lg font-bold text-slate-900 font-display">Clinic Share Code</h2><p className="text-xs text-slate-600">Temporary Health Worker Access</p></div></div><button type="button" onClick={onClose} aria-label="Close clinic share dialog" className="p-2 rounded-md text-slate-600 hover:text-slate-900 hover:bg-slate-50"><X className="w-5 h-5" aria-hidden="true"/></button></div>
 <div className="mt-5 p-6 rounded-md bg-slate-50 border border-slate-200 text-center"><span className="text-xs font-semibold uppercase tracking-wider text-slate-600">One-Time Access Code</span><div className="text-4xl font-extrabold tracking-widest text-[#33178A] font-mono tabular-nums my-2">{shareCode}</div><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-md bg-amber-50 border border-amber-200 text-amber-800 text-xs font-medium mt-1"><Timer className="w-3.5 h-3.5" aria-hidden="true"/><span>Expires in <strong className="tabular-nums">{timeFormatted}</strong></span></div><div className="flex gap-2 w-full mt-5"><button type="button" onClick={handleCopy} className="flex-1 py-2.5 px-4 rounded-md bg-white border border-slate-200 text-slate-900 text-xs font-semibold hover:bg-slate-50 flex items-center justify-center gap-1.5 shadow-sm">{copied?<Check className="w-4 h-4 text-green-700" aria-hidden="true"/>:<Copy className="w-4 h-4 text-slate-600" aria-hidden="true"/>}<span>{copied?'Copied':'Copy Code'}</span></button><button type="button" onClick={handleRegenerate} aria-label="Generate a new share code" title="Generate new code" className="p-2.5 rounded-md bg-white border border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-slate-50 shadow-sm"><RefreshCw className="w-4 h-4" aria-hidden="true"/></button></div></div>
 <div className="mt-4 p-3.5 rounded-md bg-purple-50 border border-purple-100 flex items-start gap-2.5 text-xs text-slate-700"><ShieldCheck className="w-4 h-4 text-[#33178A] shrink-0 mt-0.5" aria-hidden="true"/><p className="leading-relaxed"><strong className="text-slate-900">Share only with your clinician.</strong> This allows your licensed health care provider at the clinic to review your records and verify visits. Access automatically ends after 15 minutes or when you close the session.</p></div><div className="mt-6"><button type="button" onClick={onClose} className="w-full py-3 rounded-md bg-[#33178A] text-white font-display font-semibold text-sm shadow-sm hover:bg-[#241451]">Done</button></div></div></div></AccessibleModal>;
};
