import React from 'react';
import { Bell, Home, MessageSquare, Milestone, User, Wifi, Signal, Battery, ShieldCheck } from 'lucide-react';
import EmptyState from './EmptyState';

interface MotherViewPhoneMockupProps { onExplore?: () => void; language?: 'en' | 'sw'; }

export default function MotherViewPhoneMockup({ onExplore, language = 'en' }: MotherViewPhoneMockupProps) {
  const isSw = language === 'sw';
  return <div className="relative mx-auto w-full max-w-[340px] sm:max-w-[360px]"><div className="relative rounded-[48px] p-3 bg-slate-900 border-[3.5px] border-slate-700 shadow-[0_25px_60px_-15px_rgba(51,23,138,0.22)]"><div className="rounded-[38px] overflow-hidden bg-[#FAF7FD] text-[#1D132D] relative border border-black/10 flex flex-col min-h-[620px] font-body">
    <div className="pt-2 px-5 pb-1 flex items-center justify-between text-[11px] font-bold text-slate-800"><span>9:41</span><div className="w-22 h-4 bg-black rounded-full" /><div className="flex items-center gap-1.5 text-slate-700"><Signal className="w-3 h-3" /><Wifi className="w-3 h-3" /><Battery className="w-3.5 h-3.5" /></div></div>
    <div className="px-4 pt-2.5 pb-2 flex items-center justify-between"><div><span className="font-body text-[9px] font-bold text-[#8A8199] tracking-widest uppercase block">MomHaven</span><h4 className="font-display font-extrabold text-[16px] text-[#1D132D]">{isSw ? 'Mtazamo wa Mama' : 'Mother View'}</h4></div><div className="flex items-center gap-2"><div className="w-7 h-7 rounded-full bg-white border border-[#E8E2F2] flex items-center justify-center text-[#33178A]"><Bell className="w-3.5 h-3.5" /></div><div className="w-7 h-7 rounded-full bg-[#33178A] text-white flex items-center justify-center"><User className="w-3.5 h-3.5" /></div></div></div>
    <div className="flex-1 px-4 py-6 flex items-center"><div className="w-full bg-white rounded-2xl border border-[#E8E2F2] shadow-sm p-2"><EmptyState icon={ShieldCheck} title={isSw ? 'Hakuna rekodi bado' : 'No personal data yet'} message={isSw ? 'Rekodi za afya zitaonekana baada ya kuongezwa kwenye akaunti yako.' : 'Personal pregnancy, child, appointment, and record information will appear here after it is added to the authenticated account.'} actionLabel={onExplore ? (isSw ? 'Anza' : 'Get started') : undefined} onAction={onExplore} /></div></div>
    <div className="absolute bottom-0 left-0 right-0 h-12 bg-white border-t border-[#ECE6F5] px-2 flex items-center justify-around"><div className="flex flex-col items-center text-[#33178A]"><Home className="w-3.5 h-3.5" /><span className="text-[8.5px] mt-0.5">Today</span></div><div className="flex flex-col items-center text-[#8A8199]"><Milestone className="w-3.5 h-3.5" /><span className="text-[8.5px] mt-0.5">Journey</span></div><div className="flex flex-col items-center text-[#8A8199]"><MessageSquare className="w-3.5 h-3.5" /><span className="text-[8.5px] mt-0.5">Haven</span></div><div className="flex flex-col items-center text-[#8A8199]"><User className="w-3.5 h-3.5" /><span className="text-[8.5px] mt-0.5">Profile</span></div></div>
  </div></div></div>;
}
