import React,{useEffect,useMemo,useState} from 'react';
import {addDoc,collection,doc,getDoc,getDocs,onSnapshot,query,serverTimestamp,updateDoc,where} from 'firebase/firestore';
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithPopup,signOut} from 'firebase/auth';
import {auth,db,googleProvider} from '../lib/firebase';
import {ArrowLeft,ArrowRight,CalendarDays,Car,Check,ChevronRight,HeartHandshake,Home,KeyRound,LogIn,MapPin,ShieldCheck,UserRound,UsersRound,WifiOff} from 'lucide-react';
import EmptyState from './EmptyState';
import EmergencyFlow from './EmergencyFlow';

const grad='linear-gradient(135deg,#33178A 0%,#9167C2 100%)';
const card='rounded-[20px] border border-[#E5DFF0] bg-white shadow-[0_8px_24px_rgba(51,23,138,0.08)]';
const primary='w-full rounded-[28px] px-5 py-3.5 font-display font-bold text-white';
const secondary='w-full rounded-[28px] border-[1.5px] border-[#33178A] bg-white px-5 py-3.5 font-display font-bold text-[#33178A]';
export type PartnerScreen='home'|'appointment'|'support'|'module'|'birth_plan'|'edit_transport'|'emergency'|'profile'|'connection';

const ErrorBox=({children}:{children:React.ReactNode})=><div className="rounded-2xl bg-red-50 p-3 text-xs font-semibold text-red-700">{children}</div>;
const Field=({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string})=><label className="block"><span className="mb-1.5 block text-xs font-semibold text-[#6D6380]">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-[#E5DFF0] bg-[#F7F3FC] px-4 py-3.5 text-sm"/></label>;
const AuthPage=({title,sub,icon:Icon,children,back}:{title:string;sub:string;icon:any;children:React.ReactNode;back?:()=>void})=><div className="min-h-screen bg-[#F7F3FC] flex items-center justify-center p-4"><div className="w-full max-w-[430px] overflow-hidden rounded-[32px] bg-white shadow-[0_24px_70px_rgba(51,23,138,.18)]"><div className="p-8 text-white" style={{background:grad}}>{back&&<button onClick={back} className="mb-6 flex h-10 w-10 items-center justify-center rounded-full bg-white/15"><ArrowLeft/></button>}<div className="flex h-16 w-16 items-center justify-center rounded-[22px] bg-white/15"><Icon/></div><h1 className="mt-5 font-display text-3xl font-bold">{title}</h1><p className="mt-2 text-sm leading-6 text-white/85">{sub}</p></div><div className="space-y-3 p-6">{children}</div></div></div>;

export function PartnerAuth({onComplete}:{onComplete:()=>void}){const[s,setS]=useState<'welcome'|'signin'|'create'|'connect'|'success'>('welcome');const[email,setEmail]=useState(''),[pw,setPw]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[motherName,setMotherName]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 const fail=(e:any)=>setErr(e?.code==='auth/invalid-credential'?'Those sign-in details were not recognised.':e?.code==='auth/email-already-in-use'?'That email already has an account. Try signing in.':e?.message||'Something went wrong. Please try again.');
 const savePartner=async(u:any)=>{await updateDoc(doc(db,'users',u.uid),{role:'PARTNER',displayName:u.displayName||'Partner'}).catch(async()=>setS('connect'));};
 const create=async()=>{if(!email.trim()||pw.length<6||pw!==confirm){setErr(!email.trim()?'Enter your email.':pw.length<6?'Use at least 6 characters.':'Passwords do not match.');return}setBusy(true);setErr('');try{const r=await createUserWithEmailAndPassword(auth,email.trim(),pw);await (async()=>{const ref=doc(db,'users',r.user.uid);await updateDoc(ref,{role:'PARTNER',displayName:'Partner'}).catch(async()=>{const {setDoc}=await import('firebase/firestore');await setDoc(ref,{uid:r.user.uid,email:r.user.email||email,displayName:'Partner',role:'PARTNER',createdAt:new Date().toISOString()})})})();setS('connect')}catch(e){fail(e)}finally{setBusy(false)}};
 const login=async()=>{setBusy(true);setErr('');try{await signInWithEmailAndPassword(auth,email.trim(),pw);onComplete()}catch(e){fail(e)}finally{setBusy(false)}};
 const google=async()=>{setBusy(true);setErr('');try{const r=await signInWithPopup(auth,googleProvider);const ref=doc(db,'users',r.user.uid);const snap=await getDoc(ref);if(!snap.exists()){const {setDoc}=await import('firebase/firestore');await setDoc(ref,{uid:r.user.uid,email:r.user.email||'',displayName:r.user.displayName||'Partner',role:'PARTNER',createdAt:new Date().toISOString()})}else await updateDoc(ref,{role:'PARTNER'});onComplete()}catch(e){fail(e)}finally{setBusy(false)}};
 const connect=async()=>{const uid=auth.currentUser?.uid;if(!uid||!code.trim()){setErr('Enter the connection code she shared with you.');return}setBusy(true);setErr('');try{const snap=await getDocs(query(collection(db,'partnerRelationships'),where('code','==',code.trim()),where('status','==','pending')));if(snap.empty){setErr('That code isn’t valid or has already been used.');return}const pending=snap.docs[0],d=pending.data();if(d.motherId===uid){setErr('You cannot connect an account to itself.');return}const relationshipId=`${d.motherId}_${uid}`;await updateDoc(doc(db,'partnerRelationships',relationshipId),{motherId:d.motherId,partnerId:uid,partnerName:auth.currentUser?.displayName||'Partner',status:'active',sharedSections:['birth_plan','appointments'],createdAt:d.createdAt||serverTimestamp(),code:d.code});await updateDoc(pending.ref,{status:'used',usedBy:uid,partnerId:uid,usedAt:serverTimestamp()});setMotherName(d.motherName||'the mother');setS('success')}catch(e){fail(e)}finally{setBusy(false)}};
 if(s==='welcome')return <AuthPage title="You're part of her journey" sub="Here’s how you can support her pregnancy, appointments and birth plan." icon={UsersRound}><button className={primary} style={{background:grad}} onClick={()=>setS('create')}>Create partner account</button><button className="font-body text-sm font-semibold text-[#33178A] underline" onClick={()=>setS('signin')}>Sign in</button></AuthPage>;
 if(s==='signin')return <AuthPage title="Partner sign in" sub="Welcome back. Sign in to continue supporting her." icon={LogIn} back={()=>setS('welcome')}><Field label="Email" value={email} onChange={setEmail} type="email"/><Field label="Password" value={pw} onChange={setPw} type="password"/>{err&&<ErrorBox>{err}</ErrorBox>}<button className={primary} style={{background:grad}} onClick={login} disabled={busy}>{busy?'Signing in…':'Sign in'}</button><button className={secondary} onClick={google} disabled={busy}>Continue with Google</button></AuthPage>;
 if(s==='create')return <AuthPage title="Create partner account" sub="Create your account, then connect using the private code she shares." icon={UserRound} back={()=>setS('welcome')}><Field label="Email" value={email} onChange={setEmail} type="email"/><Field label="Password" value={pw} onChange={setPw} type="password"/><Field label="Confirm password" value={confirm} onChange={setConfirm} type="password"/>{err&&<ErrorBox>{err}</ErrorBox>}<button className={primary} style={{background:grad}} onClick={create} disabled={busy}>{busy?'Creating…':'Create account'}</button><button className={secondary} onClick={google} disabled={busy}>Continue with Google</button></AuthPage>;
 if(s==='connect')return <AuthPage title="Enter her connection code" sub="The code connects this account to the mother who chose to share her journey." icon={KeyRound} back={()=>setS('create')}><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="123456" className="w-full rounded-[20px] border-2 border-[#E5DFF0] bg-[#F7F3FC] px-4 py-5 text-center font-display text-2xl font-bold tracking-widest text-[#33178A]"/>{err&&<ErrorBox>{err}</ErrorBox>}<button className={primary} style={{background:grad}} onClick={connect} disabled={busy}>{busy?'Connecting…':'Connect'}</button></AuthPage>;
 return <AuthPage title="You’re connected" sub={`You’re now connected with ${motherName}. You’ll only see information she intentionally shares.`} icon={Check}><button className={primary} style={{background:grad}} onClick={onComplete}>Continue to Home</button></AuthPage>;
}

function useRelationship(){const[rel,setRel]=useState<any>(null);const[loading,setLoading]=useState(true);useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid){setLoading(false);return}return onSnapshot(query(collection(db,'partnerRelationships'),where('partnerId','==',uid)),s=>{const rows=s.docs.map(x=>({id:x.id,...x.data()}));rows.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));setRel(rows[0]||null);setLoading(false)},()=>{setRel(null);setLoading(false)})},[]);return{rel,loading};}
function OfflineChip(){const[offline,setOffline]=useState(typeof navigator!=='undefined'&&!navigator.onLine);useEffect(()=>{const a=()=>setOffline(false),b=()=>setOffline(true);window.addEventListener('online',a);window.addEventListener('offline',b);return()=>{window.removeEventListener('online',a);window.removeEventListener('offline',b)}},[]);return offline?<span className="fixed right-4 top-4 z-30 rounded-full bg-white/90 px-3 py-1.5 text-[10px] font-bold text-[#6D6380] shadow">You're offline</span>:null;}

export function PartnerHome({onAppointment,onSupport,onBirthPlan}:{onAppointment:()=>void;onSupport:()=>void;onBirthPlan:()=>void}){const{rel,loading}=useRelationship();const[items,setItems]=useState<any[]|null>(null);const[share,setShare]=useState<any>(null);useEffect(()=>{if(!rel||rel.status!=='active'){setItems([]);setShare(null);return}const q1=query(collection(db,'reminders'),where('userId','==',rel.motherId),where('sharedWithPartner','==',true));const unsub=onSnapshot(q1,s=>setItems(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setItems([]));getDoc(doc(db,'partnerShares',rel.motherId)).then(s=>setShare(s.exists()?s.data():null));return unsub},[rel]);if(loading)return <div className="h-24 rounded-card bg-lavender-100 animate-pulse mx-5 mt-5"/>;if(!rel||rel.status!=='active')return <div className="px-5 pt-10"><EmptyState icon={HeartHandshake} title="Not connected yet" message="Enter the connection code she shared with you to get started." actionLabel="Enter connection code" onAction={()=>window.dispatchEvent(new CustomEvent('mom-haven-partner-connect'))}/></div>;const shared=[...(items||[])];if(share?.birthPlan)shared.push({id:'birth-plan',type:'logistics',title:'Birth-plan logistics',detail:share.birthPlan.preferredFacility||'Shared birth plan'});return <div className="px-5 pb-24"><OfflineChip/><div className="rounded-[24px] p-6 text-white" style={{background:grad}}><p className="text-xs uppercase tracking-wide text-white/75">Here’s how you can help today</p><h1 className="mt-1 font-display text-2xl font-bold">Supporting {rel.partnerName&&rel.partnerName!==auth.currentUser?.displayName?rel.partnerName:'her'}</h1><p className="mt-2 text-sm text-white/85">Only information she has chosen to share appears here.</p></div><div className="mt-5"><p className="mb-2 px-0.5 text-[11px] font-semibold uppercase tracking-wide text-[#6D6380]">Shared with you</p>{items===null?<div className="h-16 rounded-card bg-lavender-100 animate-pulse"/>:shared.length===0?<EmptyState icon={CalendarDays} title="Nothing shared yet" message={`Once your connected mother shares an appointment or a task, it will show up here.`}/>:shared.map(item=><button key={item.id} onClick={item.type==='logistics'?onBirthPlan:onAppointment} className={card+' mb-3 flex w-full items-center gap-3 p-4 text-left'}><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEE7F8]">{item.type==='logistics'?<HeartHandshake className="h-5 w-5 text-[#33178A]"/>:<CalendarDays className="h-5 w-5 text-[#33178A]"/>}</div><span className="flex-1"><b className="font-display text-sm">{item.title}</b><span className="block text-xs text-[#6D6380]">{item.detail||item.dueDate}</span></span><ChevronRight className="h-4 w-4"/></button>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={onSupport} className={secondary}>Support Hub</button><button onClick={onBirthPlan} className={secondary}>Birth plan</button></div></div>}

export function PartnerAppointment(){const{rel,loading}=useRelationship();const[items,setItems]=useState<any[]|null>(null);useEffect(()=>{if(!rel||rel.status!=='active')return;return onSnapshot(query(collection(db,'reminders'),where('userId','==',rel.motherId),where('sharedWithPartner','==',true)),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setItems([]))},[rel]);const ap=items?.find(x=>x.category==='ANC'||x.category==='PNC');if(loading||items===null)return <Page title="Shared appointment"><div className="h-40 rounded-card bg-lavender-100 animate-pulse"/></Page>;return <Page title="Shared appointment">{ap?<div className={card+' p-5 space-y-3'}><h2 className="font-display text-xl font-bold">{ap.title}</h2><p className="flex gap-2 text-sm"><CalendarDays className="h-5 w-5 text-[#33178A]"/>{ap.dueDate}</p>{ap.facility&&<p className="flex gap-2 text-sm"><MapPin className="h-5 w-5 text-[#33178A]"/>{ap.facility}</p>}<button className={primary} style={{background:grad}}>Add to my calendar</button></div>:<EmptyState icon={CalendarDays} title="Nothing shared yet" message="When she shares an appointment reminder, its practical details will appear here."/>}</Page>}

const ARTICLES=[['How to support her through labour','Stay calm, listen to what she wants, help with comfort measures she prefers, keep transport arrangements ready, and help her reach the facility promptly when labour or danger signs require care.'],['Understanding danger signs','Know the warning signs she has been taught to watch for, including heavy bleeding, convulsions, severe pain, difficulty breathing and reduced movement of an unborn baby. If a danger sign appears, help her seek urgent care rather than waiting.'],['What to expect during pregnancy','Pregnancy involves routine contacts with health workers, preparation for birth and attention to changes in how the mother feels. Encourage scheduled care, practical preparation and respectful communication without making clinical decisions for her.'],['Preparing for birth together','Agree on the preferred facility, transport plan, who can accompany her and how you will communicate if plans change. Keep important phone numbers accessible and revisit the plan together as the pregnancy progresses.']];
export function PartnerSupport({onModule}:{onModule:()=>void}){const{rel}=useRelationship();const[share,setShare]=useState<any>(null);useEffect(()=>{if(rel?.status!=='active')return;getDoc(doc(db,'partnerShares',rel.motherId)).then(s=>setShare(s.exists()?s.data():null))},[rel]);const tasks=useMemo(()=>{if(!share?.birthPlan)return [];const p=share.birthPlan;return [p.transportPlan?'Review the agreed transport plan':'Confirm transport arrangements',p.preferredFacility?'Know the route to the preferred facility':'Discuss the preferred facility',p.supportPersonName?'Confirm who will accompany her':'Discuss who she would like for support'].filter(Boolean)},[share]);return <Page title="Support Hub"><p className="text-sm text-[#6D6380]">Practical, non-clinical ways to be there for her.</p>{tasks.length>0&&<div className="mt-4 space-y-2"><p className="text-[11px] font-bold uppercase tracking-wide text-[#6D6380]">Support tasks</p>{tasks.map(t=><div key={t} className={card+' flex items-center gap-3 p-4'}><Check className="h-5 w-5 text-[#1E8F5F]"/><span className="text-sm font-semibold">{t}</span></div>)}</div>}<div className="mt-5 space-y-3"><p className="text-[11px] font-bold uppercase tracking-wide text-[#6D6380]">Learn</p>{ARTICLES.map((a,i)=><button key={a[0]} onClick={onModule} className={card+' w-full p-4 text-left'}><span className="text-[10px] font-bold uppercase text-[#9167C2]">Article {i+1}</span><h2 className="mt-1 font-display text-base font-bold">{a[0]}</h2><p className="mt-1 text-xs leading-5 text-[#6D6380]">{a[1]}</p></button>)}</div></Page>}
export function PartnerModule(){return <Page title="Education"><article className={card+' p-5'}><p className="text-[10px] font-bold uppercase text-[#9167C2]">Partner education</p><h2 className="mt-2 font-display text-2xl font-bold">How to support her through labour</h2><p className="mt-3 text-sm leading-6 text-[#6D6380]">Stay calm, listen to what she wants, help with comfort measures she prefers, keep transport arrangements ready, and help her reach the facility promptly when labour or danger signs require care.</p><p className="mt-4 text-sm leading-6 text-[#6D6380]">Your role is to support her choices and help with practical needs. Clinical decisions remain with her and her health-care team.</p></article></Page>}

export function PartnerBirthPlan({onEdit}:{onEdit:()=>void}){const{rel,loading}=useRelationship();const[share,setShare]=useState<any>(null);useEffect(()=>{if(rel?.status!=='active'){setShare(null);return}return onSnapshot(doc(db,'partnerShares',rel.motherId),s=>setShare(s.exists()?s.data():null),()=>setShare(null))},[rel]);if(loading)return <Page title="Birth plan"><div className="h-40 rounded-card bg-lavender-100 animate-pulse"/></Page>;if(!share?.birthPlan)return <Page title="Birth plan"><EmptyState icon={HeartHandshake} title="Nothing shared yet" message="Her birth-plan logistics will appear here when a birth plan is available to share."/></Page>;const p=share.birthPlan;return <Page title="Birth plan"><div className="space-y-3"><div className={card+' p-4'}><p className="text-xs text-[#6D6380]">Preferred facility</p><p className="mt-1 font-display font-bold">{p.preferredFacility}</p></div><div className={card+' p-4'}><p className="text-xs text-[#6D6380]">Support person</p><p className="mt-1 font-display font-bold">{p.supportPersonName}</p></div><div className={card+' p-4'}><p className="text-xs text-[#6D6380]">Emergency logistics</p><p className="mt-1 text-sm">{p.emergencyLogistics}</p></div><div className={card+' p-4'}><p className="text-xs text-[#6D6380]">Notes</p><p className="mt-1 text-sm">{p.notes}</p></div><div className={card+' p-4'}><p className="text-xs text-[#6D6380]">Transport plan</p><p className="mt-1 font-display font-bold">{p.transportPlan||'Not recorded yet'}</p></div><button onClick={onEdit} className={secondary}>Edit transport / logistics</button></div></Page>}
export function PartnerEditTransport({onDone}:{onDone:()=>void}){const{rel}=useRelationship();const[share,setShare]=useState<any>(null),[transport,setTransport]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{if(rel?.status!=='active')return;getDoc(doc(db,'partnerShares',rel.motherId)).then(s=>{if(s.exists()){const d=s.data();setShare(d);setTransport(d.birthPlan?.transportPlan||'')}})},[rel]);const save=async()=>{if(!rel?.status||rel.status!=='active'||!share?.pregnancyId)return;setBusy(true);setError('');try{await updateDoc(doc(db,'pregnancies',share.pregnancyId),{'birthPlan.transportPlan':transport});setBusy(false);onDone()}catch(e){console.error(e);setError('The transport plan could not be updated. Your partner access may have ended.');setBusy(false)}};return <Page title="Edit transport"><p className="text-sm text-[#6D6380]">You can update transport logistics only. Other birth-plan and clinical fields remain private.</p><Field label="Transport plan" value={transport} onChange={setTransport}/>{error&&<ErrorBox>{error}</ErrorBox>}<button className={primary} style={{background:grad}} onClick={save} disabled={busy}>{busy?'Saving…':'Save transport plan'}</button></Page>}

export function PartnerEmergency(){return <div className="fixed inset-0 z-40 bg-white"><EmergencyFlow onClose={()=>window.history.back()}/></div>}
export function PartnerProfile({onConnection}:{onConnection:()=>void}){const{rel}=useRelationship();const[u,setU]=useState(auth.currentUser);const signOutNow=async()=>{await signOut(auth)};return <Page title="Profile"><div className={card+' p-5'}><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#EEE7F8]"><UserRound className="text-[#33178A]"/></div><div><p className="font-display font-bold">{u?.displayName||'Partner'}</p><p className="text-xs text-[#6D6380]">{u?.email}</p></div></div></div><button onClick={onConnection} className={card+' flex w-full items-center gap-3 p-4 text-left'}><UsersRound className="text-[#33178A]"/><span className="flex-1"><b className="font-display">Mother connection</b><span className="block text-xs text-[#6D6380]">{rel?.status==='active'?'Connected':rel?.status==='revoked'?'Access ended':'Not connected'}</span></span><ChevronRight/></button><button onClick={signOutNow} className={secondary}>Sign out</button></Page>}
export function PartnerConnection({onBack}:{onBack:()=>void}){const{rel}=useRelationship();const leave=async()=>{if(!rel)return;await updateDoc(doc(db,'partnerRelationships',rel.id),{status:'revoked',revokedAt:serverTimestamp()})};if(rel?.status==='revoked')return <Page title="Mother connection"><div className={card+' p-5'}><ShieldCheck className="h-7 w-7 text-[#6D6380]"/><h2 className="mt-3 font-display text-xl font-bold">Connection ended</h2><p className="mt-2 text-sm leading-6 text-[#6D6380]">Access to shared information has ended. If you reconnect in the future, a new connection code will be needed.</p></div><button onClick={onBack} className={secondary}>Back to profile</button></Page>;return <Page title="Mother connection"><div className={card+' p-5 space-y-4'}><div><p className="text-xs text-[#6D6380]">Connected mother</p><p className="font-display font-bold text-lg">{rel?.motherName||'Connected mother'}</p></div><div><p className="text-xs text-[#6D6380]">What you can see</p><p className="mt-1 text-sm leading-6">Only appointments, reminders and birth-plan logistics she explicitly shares with you.</p></div><div><p className="text-xs text-[#6D6380]">What you cannot see</p><p className="mt-1 text-sm leading-6">Pregnancy clinical records, child records, encounters, measurements, immunisations, nutrition/development records and clinician private notes.</p></div>{rel?.status==='active'&&<button onClick={leave} className="w-full rounded-[28px] border border-red-200 bg-white px-5 py-3.5 font-display font-bold text-red-600">Leave connection</button>}</div><button onClick={onBack} className={secondary}>Back to profile</button></Page>}

function Page({title,children}:{title?:string;children:React.ReactNode}){return <div className="min-h-screen bg-[#F7F3FC] px-5 pb-28 pt-5"><OfflineChip/>{title&&<div className="mb-5 flex items-center gap-3"><button onClick={()=>window.history.back()} className="flex h-10 w-10 items-center justify-center rounded-full bg-white border border-[#E5DFF0]"><ArrowLeft className="h-5 w-5"/></button><h1 className="font-display text-xl font-bold">{title}</h1></div>}{children}</div>}
export function PartnerNav({screen,setScreen,onEmergency}:{screen:PartnerScreen;setScreen:(s:PartnerScreen)=>void;onEmergency:()=>void}){return <nav className="fixed bottom-0 left-0 right-0 z-30 mx-auto flex max-w-[760px] items-center justify-around border-t border-[#E5DFF0] bg-white/95 px-2 py-2 backdrop-blur"><button onClick={()=>setScreen('home')} className="flex flex-col items-center gap-1 px-3 py-1 text-[10px] font-bold"><Home className="h-5 w-5"/>Home</button><button onClick={()=>setScreen('support')} className="flex flex-col items-center gap-1 px-3 py-1 text-[10px] font-bold"><HeartHandshake className="h-5 w-5"/>Support</button><button onClick={onEmergency} className="flex h-12 w-12 -translate-y-4 items-center justify-center rounded-full bg-[#E11D3C] text-white shadow-lg" aria-label="Emergency"><ShieldCheck className="h-6 w-6"/></button><button onClick={()=>setScreen('birth_plan')} className="flex flex-col items-center gap-1 px-3 py-1 text-[10px] font-bold"><Car className="h-5 w-5"/>Birth plan</button><button onClick={()=>setScreen('profile')} className="flex flex-col items-center gap-1 px-3 py-1 text-[10px] font-bold"><UserRound className="h-5 w-5"/>Profile</button></nav>}
