import React, { useState } from 'react';
import { Home, HeartPulse, ClipboardList, AlertTriangle, User, LogOut } from 'lucide-react';
import EmptyState from './EmptyState';

interface PartnerShellProps { partnerId?: string; partnerName?: string; onSignOut?: () => void; }
type PartnerTab = 'home' | 'support' | 'birthplan' | 'emergency' | 'profile';
const tabs: { id: PartnerTab; label: string; icon: React.ElementType }[] = [{ id: 'home', label: 'Home', icon: Home }, { id: 'support', label: 'Support', icon: HeartPulse }, { id: 'birthplan', label: 'Birth plan', icon: ClipboardList }, { id: 'emergency', label: 'Emergency', icon: AlertTriangle }, { id: 'profile', label: 'Profile', icon: User }];

export default function PartnerShell({ partnerName, onSignOut }: PartnerShellProps) {
  const [activeTab, setActiveTab] = useState<PartnerTab>('home'); const current = tabs.find(t => t.id === activeTab) || tabs[0]; const Icon = current.icon;
  return <div className="min-h-screen bg-[var(--lavender-50)] pb-20"><header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-[var(--border-hairline)] px-4 py-3 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider font-display font-bold text-[var(--haven-orchid)]">MomHaven Partner</p><h1 className="font-display font-extrabold text-lg">{partnerName || 'Partner View'}</h1></div>{onSignOut && <button type="button" onClick={onSignOut} aria-label="Sign out" className="w-9 h-9 rounded-full bg-[var(--lavender-50)] flex items-center justify-center cursor-pointer"><LogOut className="w-4 h-4" /></button>}</header><main className="max-w-lg mx-auto p-4"><div className="bg-white rounded-2xl border border-[var(--border-hairline)] shadow-card-1 overflow-hidden"><EmptyState icon={Icon} title={activeTab === 'home' ? 'No partner connection yet' : `No ${current.label.toLowerCase()} data yet`} message="Partner information will appear here only after a live connection and persisted records exist. No mother identity, pregnancy, facility, transport, appointment, or birth-plan data is preloaded." /></div></main><nav className="fixed bottom-0 left-0 right-0 z-20 bg-white border-t border-[var(--border-hairline)]"><div className="max-w-lg mx-auto h-16 flex items-center justify-around">{tabs.map(tab => { const TabIcon = tab.icon; return <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl cursor-pointer ${activeTab === tab.id ? 'text-[var(--haven-deep)]' : 'text-[var(--ink-400)]'}`}><TabIcon className="w-5 h-5" /><span className="text-[10px] font-display font-bold">{tab.label}</span></button>; })}</div></nav></div>;
}
