import React,{useEffect,useState} from 'react';
import {collection,getDocs,query,where} from 'firebase/firestore';
import {FileText,HeartHandshake,Check} from 'lucide-react';
import {auth,db} from '../lib/firebase';
import EmptyState from './EmptyState';
const card='rounded-[20px] border border-[#E5DFF0] bg-white shadow-[0_8px_24px_rgba(51,23,138,0.08)]';
function Page({title,children}:{title:string;children:React.ReactNode}){return <div className="min-h-screen bg-[#F7F3FC] px-5 pb-28 pt-5"><h1 className="font-display text-xl font-bold mb-5">{title}</h1>{children}</div>}
export function PartnerEducationHub({onModule}:{onModule:()=>void}){const[items,setItems]=useState<any[]|null>(null);useEffect(()=>{getDocs(query(collection(db,'educationalContent'),where('status','==','published'))).then(s=>setItems(s.docs.map(d=>({id:d.id,...d.data()})))).catch(()=>setItems([]))},[]);return <Page title="Support Hub"><p className="text-sm text-[#6D6380]">Practical, non-clinical ways to be there for her.</p><div className="mt-5"><p className="text-[11px] font-bold uppercase tracking-wide text-[#6D6380] mb-2">Learn</p>{items===null?<div className="h-20 rounded-card bg-lavender-100 animate-pulse"/>:!items.length?<EmptyState icon={FileText} title="No published modules" message="Educational modules will appear here when they are published by MomHaven Admin."/>:<div className="space-y-3">{items.map((a:any)=><button key={a.id} onClick={onModule} className={card+' w-full p-4 text-left'}><span className="text-[10px] font-bold uppercase text-[#9167C2]">{a.language||'English'}</span><h2 className="mt-1 font-display text-base font-bold">{a.title}</h2><p className="mt-1 text-xs leading-5 text-[#6D6380]">{a.body}</p></button>)}</div>}</div></Page>}
export function PartnerEducationModule(){const[item,setItem]=useState<any>(null);useEffect(()=>{getDocs(query(collection(db,'educationalContent'),where('status','==','published'))).then(s=>{const rows=s.docs.map(d=>({id:d.id,...d.data()}));setItem(rows[0]||null)}).catch(()=>setItem(null))},[]);if(!item)return <Page title="Education"><EmptyState icon={FileText} title="No published module" message="There is no published educational content available right now."/></Page>;return <Page title="Education"><article className={card+' p-5'}><p className="text-[10px] font-bold uppercase text-[#9167C2]">Partner education · {item.language||'English'}</p><h2 className="mt-2 font-display text-2xl font-bold">{item.title}</h2><p className="mt-3 text-sm leading-6 text-[#6D6380]">{item.body}</p><div className="mt-5 rounded-xl bg-[#F7F3FC] p-4 text-xs text-[#6D6380] flex gap-2"><HeartHandshake className="h-4 w-4 text-[#33178A] shrink-0"/>Your role is to support her choices and practical needs. Clinical decisions remain with her and her health-care team.</div></article></Page>}
