import React,{useState} from 'react';
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithPopup} from 'firebase/auth';
import {doc,getDoc,serverTimestamp,setDoc,updateDoc} from 'firebase/firestore';
import {ArrowLeft,Check,KeyRound,LogIn,UserRound,UsersRound} from 'lucide-react';
import {auth,db,googleProvider} from '../lib/firebase';

const grad='linear-gradient(135deg,#33178A 0%,#9167C2 100%)';
const primary='w-full rounded-[28px] px-5 py-3.5 font-display font-bold text-white';
const secondary='w-full rounded-[28px] border-[1.5px] border-[#33178A] bg-white px-5 py-3.5 font-display font-bold text-[#33178A]';
const Field=({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string})=><label className="block"><span className="mb-1.5 block text-xs font-semibold text-[#6D6380]">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-[#E5DFF0] bg-[#F7F3FC] px-4 py-3.5 text-sm"/></label>;
const Page=({title,sub,icon:Icon,children,back}:{title:string;sub:string;icon:React.ComponentType<{className?:string}>;children:React.ReactNode;back?:()=>void})=><div className="min-h-screen bg-[#F7F3FC] flex items-center justify-center p-4"><div className="w-full max-w-[430px] overflow-hidden rounded-[32px] bg-white shadow-[0_24px_70px_rgba(51,23,138,.18)]"><div className="p-8 text-white" style={{background:grad}}>{back&&<button onClick={back} className="mb-6 flex h-10 w-10 items-center justify-center rounded-full bg-white/15" aria-label="Back"><ArrowLeft/></button>}<div className="flex h-16 w-16 items-center justify-center rounded-[22px] bg-white/15"><Icon/></div><h1 className="mt-5 font-display text-3xl font-bold">{title}</h1><p className="mt-2 text-sm leading-6 text-white/85">{sub}</p></div><div className="space-y-3 p-6">{children}</div></div></div>;

export default function PartnerAuth({onComplete}:{onComplete:()=>void}){
 const[screen,setScreen]=useState<'welcome'|'signin'|'create'|'connect'|'success'>('welcome');
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[motherName,setMotherName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const fail=(e:any)=>setError(e?.code==='auth/invalid-credential'?'Those sign-in details were not recognised.':e?.code==='auth/email-already-in-use'?'That email already has an account. Try signing in.':e?.message||'Something went wrong. Please try again.');
 const create=async()=>{if(!email.trim()){setError('Enter your email.');return}if(password.length<6){setError('Use at least 6 characters.');return}if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);setError('');try{const r=await createUserWithEmailAndPassword(auth,email.trim(),password);await setDoc(doc(db,'users',r.user.uid),{uid:r.user.uid,email:r.user.email||email.trim(),displayName:r.user.displayName||'Partner',role:'PARTNER',createdAt:serverTimestamp()},{merge:true});setScreen('connect')}catch(e){fail(e)}finally{setBusy(false)}};
 const login=async()=>{setBusy(true);setError('');try{await signInWithEmailAndPassword(auth,email.trim(),password);onComplete()}catch(e){fail(e)}finally{setBusy(false)}};
 const google=async()=>{setBusy(true);setError('');try{const r=await signInWithPopup(auth,googleProvider);await setDoc(doc(db,'users',r.user.uid),{uid:r.user.uid,email:r.user.email||'',displayName:r.user.displayName||'Partner',role:'PARTNER',createdAt:serverTimestamp()},{merge:true});onComplete()}catch(e){fail(e)}finally{setBusy(false)}};
 const connect=async()=>{const uid=auth.currentUser?.uid;if(!uid||code.length!==6){setError('Enter the 6-digit connection code she shared with you.');return}setBusy(true);setError('');try{const pendingRef=doc(db,'partnerRelationships',code);const snap=await getDoc(pendingRef);if(!snap.exists()||snap.data().status!=='pending'||snap.data().code!==code){setError('That code isn’t valid or has already been used.');return}const invite=snap.data();if(invite.motherId===uid){setError('You cannot connect an account to itself.');return}const relationshipId=`${invite.motherId}_${uid}`;await setDoc(doc(db,'partnerRelationships',relationshipId),{motherId:invite.motherId,partnerId:uid,partnerName:auth.currentUser?.displayName||'Partner',motherName:invite.motherName||'the mother',status:'active',sharedSections:['birth_plan','appointments'],createdAt:invite.createdAt||serverTimestamp(),code:invite.code});await updateDoc(pendingRef,{status:'used',usedBy:uid,usedAt:serverTimestamp()});setMotherName(invite.motherName||'the mother');setScreen('success')}catch(e){fail(e)}finally{setBusy(false)}};
 if(screen==='welcome')return <Page title="You're part of her journey" sub="Here’s how you can support her pregnancy, appointments and birth plan." icon={UsersRound}><button className={primary} style={{background:grad}} onClick={()=>setScreen('create')}>Create partner account</button><button className="text-sm font-semibold text-[#33178A] underline" onClick={()=>setScreen('signin')}>Sign in</button></Page>;
 if(screen==='signin')return <Page title="Partner sign in" sub="Welcome back. Sign in to continue supporting her." icon={LogIn} back={()=>setScreen('welcome')}><Field label="Email" value={email} onChange={setEmail} type="email"/><Field label="Password" value={password} onChange={setPassword} type="password"/>{error&&<p className="rounded-2xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}<button className={primary} style={{background:grad}} onClick={login} disabled={busy}>{busy?'Signing in…':'Sign in'}</button><button className={secondary} onClick={google} disabled={busy}>Continue with Google</button></Page>;
 if(screen==='create')return <Page title="Create partner account" sub="Create your account, then connect using the private code she shares." icon={UserRound} back={()=>setScreen('welcome')}><Field label="Email" value={email} onChange={setEmail} type="email"/><Field label="Password" value={password} onChange={setPassword} type="password"/><Field label="Confirm password" value={confirm} onChange={setConfirm} type="password"/>{error&&<p className="rounded-2xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}<button className={primary} style={{background:grad}} onClick={create} disabled={busy}>{busy?'Creating…':'Create account'}</button><button className={secondary} onClick={google} disabled={busy}>Continue with Google</button></Page>;
 if(screen==='connect')return <Page title="Enter her connection code" sub="The code connects this account to the mother who chose to share her journey." icon={KeyRound} back={()=>setScreen('create')}><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="123456" className="w-full rounded-[20px] border-2 border-[#E5DFF0] bg-[#F7F3FC] px-4 py-5 text-center font-display text-2xl font-bold tracking-widest text-[#33178A]"/>{error&&<p className="rounded-2xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}<button className={primary} style={{background:grad}} onClick={connect} disabled={busy}>{busy?'Connecting…':'Connect'}</button></Page>;
 return <Page title="You’re connected" sub={`You’re now connected with ${motherName}. You’ll only see information she intentionally shares.`} icon={Check}><button className={primary} style={{background:grad}} onClick={onComplete}>Continue to Home</button></Page>;
}
