import React,{useState} from 'react';
import {doc,getDoc,serverTimestamp,setDoc,updateDoc} from 'firebase/firestore';
import {auth,db} from '../lib/firebase';
import {ArrowLeft,Check,KeyRound} from 'lucide-react';
const grad='linear-gradient(135deg,#33178A 0%,#9167C2 100%)';
export default function PartnerConnect({onDone,onBack}:{onDone:()=>void;onBack:()=>void}){
 const[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[mother,setMother]=useState('');
 const submit=async()=>{const uid=auth.currentUser?.uid;if(!uid||code.length!==6){setError('Enter the 6-digit connection code she shared with you.');return}setBusy(true);setError('');try{const pendingRef=doc(db,'partnerRelationships',code);const snap=await getDoc(pendingRef);if(!snap.exists()||snap.data().status!=='pending'||snap.data().code!==code){setError('That code isn’t valid or has already been used.');return}const d=snap.data();if(d.motherId===uid){setError('You cannot connect an account to itself.');return}const relationshipId=`${d.motherId}_${uid}`;await setDoc(doc(db,'partnerRelationships',relationshipId),{motherId:d.motherId,partnerId:uid,partnerName:auth.currentUser?.displayName||'Partner',motherName:d.motherName||'the mother',status:'active',sharedSections:['birth_plan','appointments'],createdAt:d.createdAt||serverTimestamp(),code:d.code});await updateDoc(pendingRef,{status:'used',usedBy:uid,usedAt:serverTimestamp()});setMother(d.motherName||'the mother')}catch(e){console.error(e);setError('We could not connect that code. Please check it and try again.')}finally{setBusy(false)}};
 return <div className="min-h-screen bg-[#F7F3FC] p-5"><div className="mx-auto max-w-[430px]"><button onClick={onBack} className="mb-5 flex h-10 w-10 items-center justify-center rounded-full bg-white border border-[#E5DFF0]"><ArrowLeft/></button><div className="rounded-[28px] bg-white p-6 shadow-[0_16px_50px_rgba(51,23,138,.12)]"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#EEE7F8] text-[#33178A]"><KeyRound/></div>{mother?<><h1 className="mt-5 font-display text-2xl font-bold">You’re connected</h1><p className="mt-2 text-sm leading-6 text-[#6D6380]">You’re now connected with {mother}. You’ll only see information she intentionally shares.</p><button onClick={onDone} className="mt-5 w-full rounded-[28px] px-5 py-3.5 font-display font-bold text-white" style={{background:grad}}><Check className="mr-2 inline h-4 w-4"/>Continue</button></>:<><h1 className="mt-5 font-display text-2xl font-bold">Enter her connection code</h1><p className="mt-2 text-sm leading-6 text-[#6D6380]">Enter the 6-digit code she generated from Partner Management.</p><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="123456" className="mt-5 w-full rounded-2xl border-2 border-[#E5DFF0] bg-[#F7F3FC] px-4 py-5 text-center font-display text-2xl font-bold tracking-widest text-[#33178A]"/>{error&&<p className="mt-3 rounded-2xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}<button onClick={submit} disabled={busy} className="mt-4 w-full rounded-[28px] px-5 py-3.5 font-display font-bold text-white disabled:opacity-60" style={{background:grad}}>{busy?'Connecting…':'Connect'}</button></>}</div></div></div>}
