import React, { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, doc, getDoc, getDocs, onSnapshot, query, setDoc, updateDoc, where } from 'firebase/firestore';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup } from 'firebase/auth';
import { auth, db, googleProvider } from '../lib/firebase';
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronRight, HeartHandshake, Home, LogIn, MapPin, Phone, Sparkles, UserRound, UsersRound, WifiOff } from 'lucide-react';
import EmptyState from './EmptyState';

const grad='linear-gradient(135deg,#33178A 0%,#9167C2 100%)';
const card='rounded-[20px] border border-[#E5DFF0] bg-white shadow-[0_8px_24px_rgba(51,23,138,0.08)]';
const primary='w-full rounded-[28px] px-5 py-3.5 font-display font-bold text-white';
const secondary='w-full rounded-[28px] border-[1.5px] border-[#33178A] bg-white px-5 py-3.5 font-display font-bold text-[#33178A]';

type PartnerScreen='welcome'|'signin'|'create'|'connect'|'pending'|'home'|'appointment'|'support'|'module'|'birth_plan'|'edit_transport'|'emergency'|'profile'|'connection';

export function PartnerAuth({onComplete}:{onComplete:()=>void}){
  const [s,setS]=useState<PartnerScreen>('welcome'),[email,setEmail]=useState(''),[pw,setPw]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
  const fail=(e:any)=>setErr(e?.message?.includes('invalid-credential')?'Those sign-in details were not recognised. Please try again.':e?.message?.includes('email-already-in-use')?'That email already has an account. Try signing in.':e?.message||'Something went wrong. Please try again.');
  const create=async()=>{if(!email.trim()||pw.length<6||pw!==confirm){setErr(!email.trim()?'Enter your email.':pw.length<6?'Use at least 6 characters for your password.':'Passwords do not match.');return}setBusy(true);setErr('');try{const r=await createUserWithEmailAndPassword(auth,email.trim(),pw);await setDoc(doc(db,'users',r.user.uid),{uid:r.user.uid,email:r.user.email||email.trim(),displayName:'Partner',role:'PARTNER',createdAt:new Date().toISOString()},{merge:true});setS('connect')}catch(e){fail(e)}finally{setBusy(false)}};
  const login=async()=>{setBusy(true);setErr('');try{await signInWithEmailAndPassword(auth,email.trim(),pw);onComplete()}catch(e){fail(e)}finally{setBusy(false)}};
  const google=async()=>{setBusy(true);setErr('');try{await signInWithPopup(auth,googleProvider);const u=auth.currentUser;if(u)await setDoc(doc(db,'users',u.uid),{uid:u.uid,email:u.email||'',displayName:u.displayName||'Partner',role:'PARTNER',createdAt:new Date().toISOString()},{merge:true});onComplete()}catch(e){fail(e)}finally{setBusy(false)}};
  const connect=async()=>{const uid=auth.currentUser?.uid;if(!uid||!code.trim()){setErr('Enter the connection code she shared with you.');return}setBusy(true);setErr('');try{const q=query(collection(db,'partnerConnections'),where('code','==',code.trim().toUpperCase()),where('status','==','active'));const snap=await getDocs(q);if(snap.empty){setErr('That code is not valid or has expired.');return}const c=snap.docs[0],d=c.data();await setDoc(doc(db,'partnerRelationships',`${d.motherId}_${uid}`),{motherId:d.motherId,partnerId:uid,status:'active',sharedSections:['birth_plan','appointments'],createdAt:new Date().toISOString()},{merge:true});await updateDoc(c.ref,{status:'used',usedBy:uid});setS('pending')}catch(e){fail(e)}finally{setBusy(false)}};
  if(s==='welcome')return <AuthPage title="You're part of her journey" sub="Here’s how you can support her pregnancy, appointments and birth plan." icon={UsersRound}><button className={primary} style={{background:'white',color:'#33178A'}} onClick={()=>setS('create')}>Create partner account</button><button className="font-body text-sm font-semibold text-white underline" onClick={()=>setS('signin')}>Already connected? Sign in</button></AuthPage>;
  if(s==='signin')return <AuthPage title="Partner sign in" sub="Welcome back. Sign in to continue supporting her." icon={LogIn} back={()=>setS('welcome')}><Field label="Email" value={email} set={setEmail} type="email"/><Field label="Password" value={pw} set={setPw} type="password"/>{err&&<Error>{err}</Error>}<button className={primary} style={{background:grad}} onClick={login} disabled={busy}>{busy?'Signing in…':'Sign in'}</button><button className={secondary} onClick={google} disabled={busy}>Continue with Google</button></AuthPage>;
  if(s==='create')return <AuthPage title="Create partner account" sub="Create your account, then connect using the private code she shares." icon={UserRound} back={()=>setS('welcome')}><Field label="Email" value={email} set={setEmail} type="email"/><Field label="Password" value={pw} set={setPw} type="password"/><Field label="Confirm password" value={confirm} set={setConfirm} type="password"/>{err&&<Error>{err}</Error>}<button className={primary} style={{background:grad}} onClick={create} disabled={busy}>{busy?'Creating…':'Create account'}</button><button className={secondary} onClick={google} disabled={busy}>Continue with Google</button></AuthPage>;
  if(s==='connect')return <AuthPage title="Enter her connection code" sub="The code connects this account to the mother who chose to share her journey." icon={HeartHandshake} back={()=>setS('create')}><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={16} placeholder="HAVEN-XXXX" className="w-full rounded-[20px] border-2 border-[#E5DFF0] bg-[#F7F3FC] px-4 py-5 text-center font-display text-2xl font-bold tracking-widest text-[#33178A]"/>{err&&<Error>{err}</Error>}<button className={primary} style={{background:grad}} onClick={connect} disabled={busy}>{busy?'Connecting…':'Connect'}</button><button className={secondary} onClick={()=>setErr('Ask her to open Profile → Partner and generate a new connection code.')}>I don’t have a code yet</button></AuthPage>;
  return <AuthPage title="You’re connected" sub="Your connection is ready. You’ll only see information she intentionally shares with you." icon={Check}><button className={primary} style={{background:grad}} onClick={onComplete}>Continue to Home</button><button className={secondary} onClick={()=>setS('connect')}>Try another code</button></AuthPage>;
}

function AuthPage({title,sub,icon:Icon,children,back}:{title:string;sub:string;icon:any;children:React.ReactNode;back?:()=>void}){return <div className="min-h-screen bg-[#F7F3FC] flex items-center justify-center p-4"><div className="w-full max-w-[430px] overflow-hidden rounded-[32px] bg-white shadow-[0_24px_70px_rgba(51,23,138,.18)]"><div className="p-8 text-white" style={{background:grad}}>{back&&<button onClick={back} className="mb-6 flex h-10 w-10 items-center justify-center rounded-full bg-white/15"><ArrowLeft/></button>}<div className="flex h-16 w-16 items-center justify-center rounded-[22px] bg-white/15"><Icon/></div><h1 className="mt-5 font-display text-3xl font-bold">{title}</h1><p className="mt-2 font-body text-sm leading-6 text-white/85">{sub}</p></div><div className="space-y-3 p-6">{children}</div></div></div>}
function Field({label,value,set,type}:{label:string;value:string;set:(v:string)=>void;type:string}){return <label className="block"><span className="mb-1.5 block font-body text-xs font-semibold text-[#6D6380]">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-2xl border border-[#E5DFF0] bg-[#F7F3FC] px-4 py-3.5 font-body text-sm"/></label>}
const Error=({children}:{children:React.ReactNode})=><div className="rounded-2xl bg-red-50 p-3 font-body text-xs font-semibold text-red-700">{children}</div>;

export function PartnerHome({onAppointment,onSupport,onBirthPlan}:{onAppointment:()=>void;onSupport:()=>void;onBirthPlan:()=>void}){
  const [share,setShare]=useState<any>(null);
  useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid)return;return onSnapshot(query(collection(db,'partnerRelationships'),where('partnerId','==',uid),where('status','==','active')),async s=>{if(s.empty){setShare(null);return}const rel=s.docs[0].data();const sh=await getDoc(doc(db,'partnerShares',rel.motherId));setShare(sh.exists()?sh.data():null)},()=>setShare(null))},[]);
  const mother=share?.motherName||'her';
  return <Page><header className="px-5 pt-5"><p className="font-body text-xs text-[#6D6380]">Supporting</p><h1 className="font-display text-2xl font-bold">{mother}</h1></header><section className="m-4 rounded-[24px] p-6 text-white" style={{background:grad}}><p className="font-body text-sm text-white/80">Here’s how you can help today</p><h2 className="font-display text-2xl font-bold">Support her journey</h2><p className="mt-2 font-body text-sm text-white/85">{share?.pregnancySummary||'Shared details will appear here when she chooses to share them.'}</p></section><div className="space-y-3 px-4"><p className="font-body text-[11px] font-bold uppercase tracking-wider text-[#6D6380]">Shared with you</p>{share?.appointment?<button onClick={onAppointment} className={card+' flex w-full items-center gap-3 p-4 text-left'}><CalendarDays className="text-[#33178A]"/><span><b className="font-display">Appointment</b><span className="block text-xs text-[#6D6380]">{share.appointment.date} · {share.appointment.location}</span></span><ChevronRight className="ml-auto"/></button>:<EmptyState icon={CalendarDays} title="No appointment shared yet" message="When she shares an appointment, its date, time and location will appear here." actionLabel="View appointments" onAction={onAppointment}/>}<button onClick={onBirthPlan} className={card+' flex w-full items-center gap-3 p-4 text-left'}><HeartHandshake className="text-[#33178A]"/><span><b className="font-display">Birth-plan logistics</b><span className="block text-xs text-[#6D6380]">{share?.birthPlan?'Review the shared plan':'Nothing shared yet'}</span></span><ChevronRight className="ml-auto"/></button><button onClick={onSupport} className={card+' flex w-full items-center gap-3 p-4 text-left'}><Sparkles className="text-[#9167C2]"/><span><b className="font-display">Learn</b><span className="block text-xs text-[#6D6380]">Practical ways to support during pregnancy</span></span><ChevronRight className="ml-auto"/></button></div></Page>;
}

export function PartnerAppointment(){const [share,setShare]=useState<any>(null);useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid)return;return onSnapshot(query(collection(db,'partnerRelationships'),where('partnerId','==',uid),where('status','==','active')),async s=>{if(s.empty)return;const rel=s.docs[0].data();const sh=await getDoc(doc(db,'partnerShares',rel.motherId));setShare(sh.exists()?sh.data():null)},()=>setShare(null))},[]);return <Page title="Shared appointment">{share?.appointment?<div className={card+' p-5 space-y-3'}><h2 className="font-display text-xl font-bold">Appointment</h2><p className="flex gap-2 text-sm"><CalendarDays className="h-5 w-5 text-[#33178A]"/>{share.appointment.date}</p><p className="flex gap-2 text-sm"><MapPin className="h-5 w-5 text-[#33178A]"/>{share.appointment.location}</p><button className={primary} style={{background:grad}}>Add to my calendar</button><button className={secondary}>Get directions</button></div>:<EmptyState icon={CalendarDays} title="No appointment shared yet" message="When she shares one, its date, time and location will appear here. Clinical details are never included."/>}</Page>}

export function PartnerSupport({onModule}:{onModule:()=>void}){return <Page title="Support Hub"><p className="font-body text-sm text-[#6D6380]">Practical tasks and education to help you be there for her.</p><button onClick={onModule} className={card+' w-full p-5 text-left'}><Sparkles className="text-[#9167C2]"/><h2 className="mt-2 font-display text-xl font-bold">Ways to support during pregnancy</h2><p className="mt-1 text-sm text-[#6D6380]">Listen, help with practical plans, encourage routine care, and help her reach care quickly when needed.</p></button></Page>}
export function PartnerModule(){return <Page title="Educational module"><article className={card+' p-5'}><p className="font-body text-xs font-bold uppercase text-[#9167C2]">Support</p><h2 className="mt-2 font-display text-2xl font-bold">Being there during pregnancy</h2><p className="mt-3 font-body text-sm leading-6 text-[#6D6380]">Listen, help with practical plans, encourage routine care, and make it easier for her to get help quickly when she needs it.</p></article><button className={primary} style={{background:grad}}>Mark as read</button><button className={secondary}>Next module</button></Page>}

export function PartnerBirthPlan({onEdit}:{onEdit:()=>void}){const [share,setShare]=useState<any>(null);useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid)return;return onSnapshot(query(collection(db,'partnerRelationships'),where('partnerId','==',uid),where('status','==','active')),async s=>{if(s.empty){setShare(null);return}const rel=s.docs[0].data();const sh=await getDoc(doc(db,'partnerShares',rel.motherId));setShare(sh.exists()?sh.data():null)},()=>setShare(null))},[]);if(!share?.birthPlan)return <Page title="Birth plan"><EmptyState icon={HeartHandshake} title="Birth plan not shared yet" message="She can choose to share her birth-plan logistics when ready."/></Page>;const p=share.birthPlan;return <Page title="Birth plan"><p className="text-sm text-[#6D6380]">Shared logistics, from {share.motherName||'her'}.</p>{[['Facility',p.preferredFacility],['Support person',p.supportPersonName||'Not recorded'],['Transport',p.transportPlan||'Not recorded']].map(([l,v])=><div key={l} className={card+' p-4'}><p className="text-xs text-[#6D6380]">{l}</p><p className="mt-1 font-display font-bold">{v}</p></div>)}<button onClick={onEdit} className={secondary}>Edit transport</button><div className="rounded-[20px] bg-[#EEE7F8] p-4 text-sm text-[#6D6380]">This is the logistics view she chose to share. Her clinical details stay private to her.</div></Page>}

export function PartnerEditTransport({onDone}:{onDone:()=>void}){const [share,setShare]=useState<any>(null),[transport,setTransport]=useState(''),[driver,setDriver]=useState(''),[backup,setBackup]=useState(''),[error,setError]=useState('');useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid)return;return onSnapshot(query(collection(db,'partnerRelationships'),where('partnerId','==',uid),where('status','==','active')),async s=>{if(s.empty)return;const rel=s.docs[0].data();const sh=await getDoc(doc(db,'partnerShares',rel.motherId));if(sh.exists()){setShare({id:sh.id,...sh.data()});const p=sh.data().partnerLogistics||{};setTransport(p.transportPlan||sh.data().birthPlan?.transportPlan||'');setDriver(p.driverContact||'');setBackup(p.backupPlan||'')}})},[]);const save=async()=>{if(!share?.id)return;try{await updateDoc(doc(db,'partnerShares',share.id),{partnerLogistics:{transportPlan:transport,driverContact:driver,backupPlan:backup},updatedAt:new Date().toISOString()});onDone()}catch{setError('Could not save changes. Please try again.')}};return <Page title="Edit transport / logistics"><label className="block text-xs font-semibold text-[#6D6380]">Transport plan<input value={transport} onChange={e=>setTransport(e.target.value)} className="mt-1 w-full rounded-2xl border border-[#E5DFF0] bg-white p-3.5"/></label><label className="block text-xs font-semibold text-[#6D6380]">Driver contact<input value={driver} onChange={e=>setDriver(e.target.value)} className="mt-1 w-full rounded-2xl border border-[#E5DFF0] bg-white p-3.5"/></label><label className="block text-xs font-semibold text-[#6D6380]">Backup plan<textarea value={backup} onChange={e=>setBackup(e.target.value)} className="mt-1 w-full rounded-2xl border border-[#E5DFF0] bg-white p-3.5" rows={3}/></label>{error&&<Error>{error}</Error>}<button onClick={save} className={primary} style={{background:grad}}>Save changes</button><button onClick={onDone} className={secondary}>Cancel</button></Page>}

export function PartnerEmergency(){const signs=['Vaginal bleeding','Severe headache','Blurred vision','Convulsions','Severe abdominal pain','Reduced baby movement','Fever'];const [danger,setDanger]=useState(false);return <div className="min-h-screen bg-[#E11D3C] text-white"><header className="px-5 py-5"><p className="font-body text-xs font-bold tracking-wider">EMERGENCY</p><h1 className="font-display text-3xl font-bold">Get help quickly.</h1></header><main className="mx-auto max-w-[430px] space-y-3 p-5">{danger?<><h2 className="font-display text-2xl font-bold">Danger signs</h2>{signs.map(x=><label key={x} className="flex min-h-[56px] items-center gap-3 rounded-[18px] bg-white px-4 font-display font-bold text-[#241451]"><input type="checkbox" className="h-6 w-6 accent-[#E11D3C]"/>{x}</label>)}</>:<><div className="rounded-[22px] bg-white p-5 text-[#241451]"><p className="font-display text-xl font-bold">Emergency guidance works offline.</p><p className="mt-2 text-sm text-[#6D6380]">This pathway does not depend on HavenChat or a network connection.</p></div><button onClick={()=>setDanger(true)} className="w-full rounded-[20px] bg-white p-5 text-left font-display font-bold text-[#241451]">Danger signs <ChevronRight className="float-right"/></button><button className="w-full rounded-[20px] bg-white p-5 text-left font-display font-bold text-[#241451]">Facility & directions <ChevronRight className="float-right"/></button></>}<span className="inline-flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 text-xs"><WifiOff className="h-4 w-4"/>Available offline</span><a href="tel:999" className="flex min-h-[56px] items-center justify-center gap-2 rounded-[28px] bg-white px-5 font-display font-bold text-[#E11D3C]"><Phone/>Call facility now</a></main></div>}

export function PartnerProfile({onConnection}:{onConnection:()=>void}){return <Page title="Profile"><div className={card+' p-5'}><p className="text-xs text-[#6D6380]">Partner account</p><p className="mt-1 font-display font-bold">{auth.currentUser?.email||'Partner'}</p></div><button className={secondary}>Edit personal info</button><button onClick={onConnection} className={card+' flex w-full items-center justify-between p-4 text-left font-display font-bold'}>Mother connection<ChevronRight/></button><button onClick={()=>auth.signOut()} className="w-full py-3 font-display font-bold text-[#E11D3C]">Sign out</button></Page>}
export function PartnerConnection({onBack}:{onBack:()=>void}){const [rel,setRel]=useState<any>(null);useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid)return;return onSnapshot(query(collection(db,'partnerRelationships'),where('partnerId','==',uid)),s=>setRel(s.empty?null:{id:s.docs[0].id,...s.docs[0].data()}))},[]);return <Page title="Mother connection"><div className={card+' p-5'}><p className="text-xs text-[#6D6380]">Connection status</p><p className="mt-1 font-display text-xl font-bold">{rel?.status==='active'?'Connected':rel?.status==='revoked'?'Connection ended':'Not connected'}</p><p className="mt-2 text-sm text-[#6D6380]">Partner permissions are limited to information the mother intentionally shares.</p></div>{rel?.status==='active'&&<button onClick={async()=>{await updateDoc(doc(db,'partnerRelationships',rel.id),{status:'revoked',revokedAt:new Date().toISOString()});onBack()}} className={secondary}>Leave connection</button>}{rel?.status==='revoked'&&<button className={primary} style={{background:grad}}>Request new code</button>}</Page>}

export function PartnerNav({screen,setScreen,onEmergency}:{screen:PartnerScreen;setScreen:(s:PartnerScreen)=>void;onEmergency:()=>void}){return <nav className="fixed bottom-0 left-1/2 z-40 flex w-full max-w-[430px] -translate-x-1/2 items-center justify-around border-t border-[#E5DFF0] bg-white/95 px-1 py-2 backdrop-blur"><N l="Home" i={Home} a={screen==='home'} c={()=>setScreen('home')}/><N l="Support" i={HeartHandshake} a={screen==='support'||screen==='module'} c={()=>setScreen('support')}/><N l="Appointments" i={CalendarDays} a={screen==='appointment'} c={()=>setScreen('appointment')}/><N l="Birth plan" i={HeartHandshake} a={screen==='birth_plan'||screen==='edit_transport'} c={()=>setScreen('birth_plan')}/><N l="Profile" i={UserRound} a={screen==='profile'||screen==='connection'} c={()=>setScreen('profile')}/><button aria-label="Emergency" onClick={onEmergency} className="fixed bottom-16 right-3 flex h-14 w-14 items-center justify-center rounded-full bg-[#E11D3C] font-display text-xl font-bold text-white shadow-lg">!</button></nav>}
function N({l,i:I,a,c}:{l:string;i:any;a:boolean;c:()=>void}){return <button onClick={c} className={'flex min-w-14 flex-col items-center rounded-full px-1 py-1 '+(a?'bg-[#EEE7F8] text-[#33178A]':'text-[#8B8299]')}><I className="h-4 w-4"/><span className="text-[9px]">{l}</span></button>}
function Page({title,children}:{title?:string;children:React.ReactNode}){return <div className="min-h-screen bg-[#F7F3FC] flex justify-center pb-16"><div className="w-full max-w-[430px] min-h-screen bg-[#F7F3FC]"><header className="flex items-center gap-3 border-b border-[#E5DFF0] bg-white px-5 py-4"><img src="/logo.svg" className="h-8 w-8 object-contain"/><h1 className="font-display text-lg font-bold">{title||'Partner Home'}</h1></header><main className="space-y-4 pb-24">{children}</main></div></div>}
