import React,{useEffect,useState} from 'react';
import {collection,getDocs,query,where} from 'firebase/firestore';
import {FileText,HeartHandshake} from 'lucide-react';
import {auth,db} from '../lib/firebase';
import EmptyState from './EmptyState';
const card='rounded-xl border border-[#E5E7EB] bg-white shadow-sm';
function Page({title,children}:{title:string;children:React.ReactNode}){return <div className="min-h-screen bg-[#FAFAFC] px-5 pb-28 pt-5"><h1 className="mb-5 text-xl font-bold text-[#1C2833]">{title}</h1>{children}</div>}
export function PartnerEducationHub({onModule}:{onModule:()=>void}){const[items,setItems]=useState<any[]|null>(null);useEffect(()=>{getDocs(query(collection(db,'educationalContent'),where('status','==','published'))).then(s=>setItems(s.docs.map(d=>({id:d.id,...d.data()})))).catch(()=>setItems([]))},[]);return <Page title="Support Hub"><p className="text-sm text-[#566573]">Practical, non-clinical ways to be there for her.</p><div className="mt-5"><p className="mb-2 text-[11px] font-bold uppercase tracking-wide text-[#566573]">Learn</p>{items===null?<div className="h-20 rounded-xl border border-[#E5E7EB] bg-white animate-pulse"/>:!items.length?<EmptyState icon={FileText} title="No published modules" message="Educational modules will appear here when they are published by MomHaven Admin."/>:<div className="space-y-3">{items.map((a:any)=><button key={a.id} onClick={onModule} className={card+' w-full p-4 text-left'}><span className="font-mono text-[10px] font-bold uppercase text-[#8E44AD]">{a.language||'English'}</span><h2 className="mt-1 text-base font-bold text-[#1C2833]">{a.title}</h2><p className="mt-1 text-xs leading-5 text-[#566573]">{a.body}</p></button>)}</div>}</div></Page>}
export function PartnerEducationModule(){const[item,setItem]=useState<any>(null);useEffect(()=>{getDocs(query(collection(db,'educationalContent'),where('status','==','published'))).then(s=>{const rows=s.docs.map(d=>({id:d.id,...d.data()}));setItem(rows[0]||null)}).catch(()=>setItem(null))},[]);if(!item)return <Page title="Education"><EmptyState icon={FileText} title="No published module" message="There is no published educational content available right now."/></Page>;return <Page title="Education"><article className={card+' p-5'}><p className="font-mono text-[10px] font-bold uppercase text-[#8E44AD]">Partner education · {item.language||'English'}</p><h2 className="mt-2 text-2xl font-bold text-[#1C2833]">{item.title}</h2><p className="mt-3 text-sm leading-6 text-[#566573]">{item.body}</p><div className="mt-5 flex gap-2 rounded-xl border border-[#E5E7EB] bg-[#F5EEF8] p-4 text-xs text-[#566573]"><HeartHandshake className="h-4 w-4 shrink-0 text-[#5B2C6F]"/>Your role is to support her choices and practical needs. Clinical decisions remain with her and her health-care team.</div></article></Page>}
