import React from 'react';
import { ArrowLeft, Share2, Luggage } from 'lucide-react';
import { Pregnancy } from '../../types';
import EmptyState from '../EmptyState';

interface BirthPlanViewProps { pregnancy: Pregnancy; onBack: () => void; onPlanUpdated: () => void; }

export default function BirthPlanView({ pregnancy, onBack }: BirthPlanViewProps) {
  const plan = pregnancy.birthPlan;
  return <div className="min-h-screen bg-[var(--lavender-50)] pb-28"><div className="px-5 pt-6 pb-4 bg-white border-b border-[var(--border-hairline)] sticky top-0 z-10 flex items-center justify-between"><button type="button" onClick={onBack} className="w-10 h-10 rounded-full bg-[var(--lavender-50)] flex items-center justify-center cursor-pointer"><ArrowLeft className="w-5 h-5" /></button><div className="text-center"><h1 className="font-display font-extrabold text-[17px] text-[var(--ink-900)]">Individualized Birth Plan</h1><span className="text-[11px] font-semibold text-[var(--haven-orchid)]">BPCR Readiness</span></div><button type="button" aria-label="Share birth plan" disabled={!plan} className="w-10 h-10 rounded-full bg-[var(--lavender-50)] flex items-center justify-center text-[var(--haven-deep)] disabled:opacity-40 cursor-pointer"><Share2 className="w-4 h-4" /></button></div><div className="p-4 sm:p-6 max-w-lg mx-auto"><div className="bg-white rounded-[22px] border border-[var(--border-hairline)] shadow-card-1 overflow-hidden"><EmptyState icon={Luggage} title={plan ? 'Birth plan data is available' : 'No birth plan yet'} message={plan ? 'Your individualized birth plan is ready to be populated into the detailed planning view.' : 'Birth facilities, transport, companions, donors, funds, and hospital-bag items will appear here after you create a birth plan. No example values are preloaded.'} /></div>{plan && <div className="mt-4 bg-white rounded-[20px] border border-[var(--border-hairline)] p-4 space-y-2 text-sm text-[var(--ink-700)]">{plan.preferredFacility && <p><strong>Primary facility:</strong> {plan.preferredFacility}</p>}{plan.backupFacility && <p><strong>Backup facility:</strong> {plan.backupFacility}</p>}{plan.transportMode && <p><strong>Transport:</strong> {plan.transportMode}</p>}{plan.birthCompanion && <p><strong>Birth companion:</strong> {plan.birthCompanion}</p>}{plan.bloodDonorName && <p><strong>Blood donor:</strong> {plan.bloodDonorName}</p>}</div>}</div></div>;
}
