/** @license Apache-2.0 */
import React,{useState,useEffect} from 'react';
import {signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendPasswordResetEmail,onAuthStateChanged,signOut,User as FirebaseUser} from 'firebase/auth';
import {doc,getDoc,setDoc,addDoc,collection,serverTimestamp} from 'firebase/firestore';
import {auth,googleProvider,db} from './lib/firebase';
import {UserRole,UserDoc,MotherProfileDoc,Provenance} from './types';
import {WelcomeScreen} from './components/auth/WelcomeScreen'; import {SignInScreen} from './components/auth/SignInScreen'; import {CreateAccountScreen} from './components/auth/CreateAccountScreen'; import {ForgotPasswordScreen} from './components/auth/ForgotPasswordScreen'; import {InitialProfileSetup} from './components/auth/InitialProfileSetup'; import {PregnancySetup} from './components/auth/PregnancySetup'; import {AddPregnancyHistory} from './components/auth/AddPregnancyHistory';
import {MotherLayout} from './components/MotherLayout'; import {PartnerLayout} from './components/PartnerLayout'; import PartnerAuth from './components/PartnerAuth'; import {ClinicianLayout} from './components/ClinicianLayout'; import {AdminLayout} from './components/AdminLayout'; import AdminAuth from './components/AdminAuth'; import {EmergencyModal} from './components/EmergencyModal'; import {AppLockGate} from './components/AppLockGate'; import {LogOut,Loader2} from 'lucide-react';
type AuthView='welcome'|'signin'|'create_account'|'forgot_password'; type OnboardingStage='profile_setup'|'pregnancy_setup'|'pregnancy_history';
export default function App(){const[currentUser,setCurrentUser]=useState<FirebaseUser|null>(null);const[userProfile,setUserProfile]=useState<UserDoc|null>(null);const[motherProfile,setMotherProfile]=useState<MotherProfileDoc|null>(null);const[loading,setLoading]=useState(true);const[googleLoading,setGoogleLoading]=useState(false);const[authView,setAuthView]=useState<AuthView>('welcome');const[partnerEntry,setPartnerEntry]=useState(false);const[isOnboarding,setIsOnboarding]=useState(false);const[onboardingStage,setOnboardingStage]=useState<OnboardingStage>('profile_setup');const[activePregnancyId,setActivePregnancyId]=useState<string|null>(null);const[isEmergencyOpen,setIsEmergencyOpen]=useState(false);const isAdminPortal=typeof window!=='undefined'&&window.location.pathname.startsWith('/admin');
useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){setCurrentUser(null);setUserProfile(null);setMotherProfile(null);setIsOnboarding(false);setLoading(false);return}setCurrentUser(u);try{const ref=doc(db,'users',u.uid);const snap=await getDoc(ref);let data:UserDoc;if(snap.exists())data=snap.data() as UserDoc;else{data={uid:u.uid,email:u.email||'',displayName:u.displayName||'Mama',role:'MOTHER' as UserRole,createdAt:new Date().toISOString()};await setDoc(ref,{...data,createdAt:serverTimestamp()})}setUserProfile(data);if(data.role==='MOTHER'){const ms=await getDoc(doc(db,'motherProfiles',u.uid));if(ms.exists()){setMotherProfile(ms.data() as MotherProfileDoc);setIsOnboarding(false)}else{setIsOnboarding(true);setOnboardingStage('profile_setup')}}else{setMotherProfile(null);setIsOnboarding(false)}}catch(e){console.error(e);setUserProfile({uid:u.uid,email:u.email||'',displayName:u.displayName||'Mama',role:'MOTHER',createdAt:new Date().toISOString()});setIsOnboarding(false)}finally{setLoading(false)} }),[]);
const handleGoogleSignIn=async()=>{setGoogleLoading(true);try{await signInWithPopup(auth,googleProvider)}finally{setGoogleLoading(false)}};const handleEmailSignIn=async(e:string,p:string)=>{await signInWithEmailAndPassword(auth,e,p)};const handleEmailSignUp=async(e:string,p:string,n:string)=>{const r=await createUserWithEmailAndPassword(auth,e,p);const d:UserDoc={uid:r.user.uid,email:r.user.email||e,displayName:n||'Mama',role:'MOTHER',createdAt:new Date().toISOString()};await setDoc(doc(db,'users',r.user.uid),{...d,createdAt:serverTimestamp()});setUserProfile(d);setIsOnboarding(true);setOnboardingStage('profile_setup')};const reset=async(e:string)=>sendPasswordResetEmail(auth,e);const logout=async()=>signOut(auth);const finishPartnerEntry=async()=>{setPartnerEntry(false);setIsOnboarding(false);const u=auth.currentUser;if(u){try{const snap=await getDoc(doc(db,'users',u.uid));if(snap.exists())setUserProfile(snap.data() as UserDoc)}catch(e){console.error(e)}}};
const pregnancy=async(data:{method:'LMP'|'EDD';date:string;calculatedEDD:string;calculatedWeeks:number})=>{if(!currentUser)return;const input=new Date(`${data.date}T00:00:00`);const lmpDate=data.method==='LMP'?input:new Date(input);if(data.method==='EDD')lmpDate.setDate(lmpDate.getDate()-280);const provenance:Provenance={status:'REPORTED',enteredBy:currentUser.uid,enteredAt:new Date().toISOString(),verifiedBy:null,verifiedAt:null};const r=await addDoc(collection(db,'pregnancies'),{motherId:currentUser.uid,lmp:lmpDate.toISOString().slice(0,10),edd:data.calculatedEDD,status:'active',calculationMethod:data.method,currentWeek:data.calculatedWeeks,provenance,createdAt:serverTimestamp()});setActivePregnancyId(r.id);setOnboardingStage('pregnancy_history')};
if(loading)return <div className="min-h-screen bg-[#F7F3FC] flex flex-col items-center justify-center text-[#241451]"><Loader2 className="h-8 w-8 animate-spin text-[#33178A]"/><p className="mt-3 font-display font-bold">Loading MomHaven…</p></div>;
if(isAdminPortal)return currentUser&&userProfile?.role==='ADMIN'?<AdminAuth onSuccess={()=>{}}/>:<AdminAuth onSuccess={()=>{}}/>;
if(partnerEntry)return <PartnerAuth onComplete={finishPartnerEntry}/>;
if(!currentUser)return <div className="min-h-screen bg-[#F7F3FC] flex items-center justify-center p-3 sm:p-6">{authView==='welcome'&&<WelcomeScreen onCreateAccount={()=>setAuthView('create_account')} onSignIn={()=>setAuthView('signin')} onGoogleSignIn={handleGoogleSignIn} googleLoading={googleLoading} onPartner={()=>setPartnerEntry(true)}/>} {authView==='signin'&&<SignInScreen onBack={()=>setAuthView('welcome')} onSuccess={()=>{}} onCreateAccount={()=>setAuthView('create_account')} onForgotPassword={()=>setAuthView('forgot_password')} onGoogleSignIn={handleGoogleSignIn} onEmailSignIn={handleEmailSignIn} googleLoading={googleLoading}/>} {authView==='create_account'&&<CreateAccountScreen onBack={()=>setAuthView('welcome')} onSignIn={()=>setAuthView('signin')} onSuccess={()=>{}} onGoogleSignIn={handleGoogleSignIn} onEmailSignUp={handleEmailSignUp} googleLoading={googleLoading}/>} {authView==='forgot_password'&&<ForgotPasswordScreen onBack={()=>setAuthView('signin')} onSendResetEmail={reset}/>}</div>;
if(isOnboarding&&userProfile)return <div className="min-h-screen bg-[#F7F3FC] flex items-center justify-center p-3 sm:p-6">{onboardingStage==='profile_setup'&&<InitialProfileSetup user={userProfile} onBack={logout} onContinue={p=>{setMotherProfile(x=>({...x,...p} as MotherProfileDoc));setOnboardingStage('pregnancy_setup')}}/>}{onboardingStage==='pregnancy_setup'&&<PregnancySetup onBack={()=>setOnboardingStage('profile_setup')} onContinue={pregnancy} onSkip={()=>setOnboardingStage('pregnancy_history')}/>} {onboardingStage==='pregnancy_history'&&<AddPregnancyHistory userId={currentUser.uid} pregnancyId={activePregnancyId||undefined} onBack={()=>setOnboardingStage('pregnancy_setup')} onComplete={()=>setIsOnboarding(false)} onSkip={()=>setIsOnboarding(false)}/>}</div>;
const role=userProfile?.role||'MOTHER';return <AppLockGate><div className="min-h-screen bg-[#F7F3FC] text-[#241451] flex flex-col font-body">{role!=='ADMIN'&&<header className="w-full bg-white border-b border-[#E5DFF0] px-4 py-2.5 text-xs flex items-center justify-between"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[#1E8F5F]"/><span className="font-display font-bold">{userProfile?.displayName||currentUser.email}</span><span className="rounded-full bg-[#EEE7F8] px-2 py-0.5 font-display text-[11px] font-bold text-[#33178A]">{role}</span></div><button onClick={logout} className="flex items-center gap-1.5 font-display font-semibold text-[#6D6380]"><LogOut className="h-3.5 w-3.5"/>Sign out</button></div></header>}<main className="flex-1 w-full mx-auto">{role==='MOTHER'&&<MotherLayout user={userProfile||{uid:currentUser.uid,email:currentUser.email||'',displayName:currentUser.displayName||'Mama',role:'MOTHER',createdAt:new Date().toISOString()}} motherProfile={motherProfile} onOpenEmergency={()=>setIsEmergencyOpen(true)}/>} {role==='PARTNER'&&<PartnerLayout onOpenEmergency={()=>setIsEmergencyOpen(true)}/>} {role==='CLINICIAN'&&<ClinicianLayout/>}{role==='ADMIN'&&<AdminLayout user={userProfile||undefined} onSignOut={logout}/>}</main><EmergencyModal isOpen={isEmergencyOpen} onClose={()=>setIsEmergencyOpen(false)}/></div></AppLockGate>}
