import React, { useState } from 'react';
import { Home, Milestone, MessageSquare, FileText, User, ArrowLeft, ShieldCheck } from 'lucide-react';
import EmptyState from '../EmptyState';

type MotherTab = 'today' | 'journey' | 'haven' | 'records' | 'profile';
interface AnonymousMotherShellProps { onBackToLanding: () => void; onCreateAccount: () => void; initialTab?: MotherTab; }

const tabs: { id: MotherTab; label: string; icon: React.ElementType }[] = [
  { id: 'today', label: 'Today', icon: Home }, { id: 'journey', label: 'Journey', icon: Milestone }, { id: 'haven', label: 'Haven', icon: MessageSquare }, { id: 'records', label: 'Records', icon: FileText }, { id: 'profile', label: 'Profile', icon: User },
];

export default function AnonymousMotherShell({ onBackToLanding, onCreateAccount, initialTab = 'today' }: AnonymousMotherShellProps) {
  const [activeTab, setActiveTab] = useState<MotherTab>(initialTab); const current = tabs.find(t => t.id === activeTab) || tabs[0]; const Icon = current.icon;
  return <div className="min-h-screen bg-[var(--lavender-50)] pb-20"><header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-[var(--border-hairline)] px-4 py-3 flex items-center justify-between"><button type="button" onClick={onBackToLanding} className="w-9 h-9 rounded-full bg-[var(--lavender-50)] flex items-center justify-center cursor-pointer" aria-label="Back"><ArrowLeft className="w-4 h-4" /></button><div className="text-center"><p className="text-[10px] uppercase tracking-wider font-display font-bold text-[var(--haven-orchid)]">MomHaven</p><h1 className="font-display font-extrabold text-lg">{current.label}</h1></div><button type="button" onClick={onCreateAccount} className="text-[11px] font-display font-bold text-[var(--haven-deep)] cursor-pointer">Create account</button></header><main className="max-w-lg mx-auto p-4"><div className="mb-4 bg-white rounded-2xl border border-[var(--border-hairline)] p-4 flex items-start gap-3"><ShieldCheck className="w-5 h-5 text-[var(--haven-deep)] shrink-0" /><p className="text-xs text-[var(--ink-600)]">You are exploring without personal records. Nothing below is preloaded with a fictional pregnancy, child, appointment, clinician, or health history.</p></div><div className="bg-white rounded-2xl border border-[var(--border-hairline)] shadow-card-1 overflow-hidden"><EmptyState icon={Icon} title={`No ${current.label.toLowerCase()} data yet`} message="Sign in or create an account to add and securely store your own information. Anonymous exploration does not display sample personal data." /></div></main><nav className="fixed bottom-0 left-0 right-0 z-20 bg-white border-t border-[var(--border-hairline)]"><div className="max-w-lg mx-auto h-16 flex items-center justify-around">{tabs.map(tab => { const TabIcon = tab.icon; return <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl cursor-pointer ${activeTab === tab.id ? 'text-[var(--haven-deep)]' : 'text-[var(--ink-400)]'}`}><TabIcon className="w-5 h-5" /><span className="text-[10px] font-display font-bold">{tab.label}</span></button>; })}</div></nav></div>;
}
